import type { AchievementDef } from './schema';

export const ACHIEVEMENTS: readonly AchievementDef[] = [
  {
    id: 'first-wedge',
    name: 'First Wedge',
    description: 'Bank a single piece of cheese. Gran will pretend she is not proud.',
    target: 1,
    hidden: false,
    metric: 'cheeseTotal',
  },
  {
    id: 'nibble-dozen',
    name: 'Nibble Dozen',
    description: 'Bank 12 cheese across any modes. The pantry notices.',
    target: 12,
    hidden: false,
    metric: 'cheeseTotal',
  },
  {
    id: 'wheel-thief',
    name: 'Wheel Thief',
    description: 'Bank 50 cheese. Pounce starts taking the job personally.',
    target: 50,
    hidden: false,
    metric: 'cheeseTotal',
  },
  {
    id: 'larder-emptied',
    name: 'Larder Emptied',
    description: 'Bank 150 cheese. The house develops a mouse-shaped budget crisis.',
    target: 150,
    hidden: false,
    metric: 'cheeseTotal',
  },
  {
    id: 'legend-of-the-wedge',
    name: 'Legend of the Wedge',
    description: 'Bank 400 cheese. Future cats will study this as a cautionary tale.',
    target: 400,
    hidden: true,
    metric: 'cheeseTotal',
  },
  {
    id: 'crumb-trail-clear',
    name: 'Out the Hole',
    description: 'Clear any stage by filling the quota and reaching the hole.',
    target: 1,
    hidden: false,
    metric: 'stagesCleared',
  },
  {
    id: 'kitchen-graduate',
    name: 'Kitchen Graduate',
    description: 'Clear 8 stages. You know which boards creak.',
    target: 8,
    hidden: false,
    metric: 'stagesCleared',
  },
  {
    id: 'night-shift',
    name: 'Night Shift',
    description: 'Clear 24 stages. The house is a map in your teeth.',
    target: 24,
    hidden: false,
    metric: 'stagesCleared',
  },
  {
    id: 'protocol-complete',
    name: 'Protocol Complete',
    description: 'Clear 96 story stages. The moon lab files you as a known anomaly.',
    target: 96,
    hidden: false,
    metric: 'stagesCleared',
  },
  {
    id: 'ghost-mouse',
    name: 'Ghost Mouse',
    description: 'Clear a stage without being caught. Pounce will claim the cheese walked itself.',
    target: 1,
    hidden: false,
    metric: 'noCatchClears',
  },
  {
    id: 'untouchable',
    name: 'Untouchable',
    description: 'Clear 10 stages with no catches. The sight cone starts to feel optional.',
    target: 10,
    hidden: false,
    metric: 'noCatchClears',
  },
  {
    id: 'rumour',
    name: 'Rumour',
    description: 'Clear 25 stages with no catches. You are a draft under the door.',
    target: 25,
    hidden: true,
    metric: 'noCatchClears',
  },
  {
    id: 'first-dash',
    name: 'Spark',
    description: 'Dash once. Stamina is a resource; panic is a lifestyle.',
    target: 1,
    hidden: false,
    metric: 'dashCount',
  },
  {
    id: 'floorboard-blur',
    name: 'Floorboard Blur',
    description: 'Dash 50 times. The cat learns to lead the shot.',
    target: 50,
    hidden: false,
    metric: 'dashCount',
  },
  {
    id: 'stamina-poet',
    name: 'Stamina Poet',
    description: 'Dash 200 times. You have opinions about dash cooldown.',
    target: 200,
    hidden: false,
    metric: 'dashCount',
  },
  {
    id: 'first-decoy',
    name: 'Look Over There',
    description: 'Drop a decoy that a cat actually investigates.',
    target: 1,
    hidden: false,
    metric: 'decoyCount',
  },
  {
    id: 'yarn-budget',
    name: 'Yarn Budget',
    description: 'Use 20 decoys. The living room is a crime scene of red thread.',
    target: 20,
    hidden: false,
    metric: 'decoyCount',
  },
  {
    id: 'puppeteer',
    name: 'Puppeteer',
    description: 'Use 75 decoys. Cats have started naming the yarn.',
    target: 75,
    hidden: true,
    metric: 'decoyCount',
  },
  {
    id: 'first-nibble-buff',
    name: 'Pocket Science',
    description: 'Use any power-up. Pepper is a legitimate tactic.',
    target: 1,
    hidden: false,
    metric: 'powerUpsUsed',
  },
  {
    id: 'pantry-alchemist',
    name: 'Pantry Alchemist',
    description: 'Use 25 power-ups. You have a favourite and will not be reasoned with.',
    target: 25,
    hidden: false,
    metric: 'powerUpsUsed',
  },
  {
    id: 'lab-mouse',
    name: 'Lab Mouse',
    description: 'Use 80 power-ups. The moon lab would like its ice cube back.',
    target: 80,
    hidden: false,
    metric: 'powerUpsUsed',
  },
  {
    id: 'chapter-one-done',
    name: 'Gran\'s Kitchen',
    description: 'Clear chapter 1. The fridge light no longer startles you.',
    target: 1,
    hidden: false,
    metric: 'chapterCleared',
  },
  {
    id: 'halfway-house',
    name: 'Halfway House',
    description: 'Clear 6 chapters. The carnival is still closed and you are still hungry.',
    target: 6,
    hidden: false,
    metric: 'chapterCleared',
  },
  {
    id: 'full-protocol',
    name: 'Full Protocol',
    description: 'Clear all 12 chapters. Squeak files a report. Pounce files a complaint.',
    target: 12,
    hidden: false,
    metric: 'chapterCleared',
  },
  {
    id: 'double-nibble',
    name: 'Double Nibble',
    description: 'Hit a combo of 4. The hole starts to feel like a bank teller.',
    target: 4,
    hidden: false,
    metric: 'comboBest',
  },
  {
    id: 'wedge-storm',
    name: 'Wedge Storm',
    description: 'Hit a combo of 8. Even the Radio is impressed, which is rare.',
    target: 8,
    hidden: false,
    metric: 'comboBest',
  },
  {
    id: 'clock-watcher',
    name: 'Clock Watcher',
    description: 'Finish a time-attack stage under par. The pendulum hates you.',
    target: 1,
    hidden: false,
    metric: 'timeAttackBest',
  },
  {
    id: 'pendulum-breaker',
    name: 'Pendulum Breaker',
    description: 'Beat par on 6 time-attack layouts. Thirteen o\'clock can wait.',
    target: 6,
    hidden: false,
    metric: 'timeAttackBest',
  },
  {
    id: 'ice-manners',
    name: 'Ice Manners',
    description: 'Freeze a cat once. They remember.',
    target: 1,
    hidden: false,
    metric: 'catsFrozen',
  },
  {
    id: 'glacier-mouse',
    name: 'Glacier Mouse',
    description: 'Freeze cats 20 times. The freezer is now a strategic asset.',
    target: 20,
    hidden: false,
    metric: 'catsFrozen',
  },
  {
    id: 'absolute-zero',
    name: 'Absolute Zero',
    description: 'Freeze cats 60 times. The sphynx has filed a temperature grievance.',
    target: 60,
    hidden: true,
    metric: 'catsFrozen',
  },
];

export const ACHIEVEMENT_BY_ID: Readonly<Record<string, AchievementDef>> = Object.fromEntries(
  ACHIEVEMENTS.map((achievement) => [achievement.id, achievement]),
);

export const ACHIEVEMENT_IDS: readonly string[] = ACHIEVEMENTS.map((achievement) => achievement.id);
