import type { BreedDef } from './schema';

export const BREEDS: readonly BreedDef[] = [
  {
    id: 'tabby',
    name: 'Tabby',
    blurb: 'The neighbourhood regular. Walks a beat, trusts both ears and nose, rarely commits to a pounce until sure.',
    color: '#c47a3a',
    stats: {
      patrolSpeed: 1.15,
      investigateSpeed: 1.45,
      chaseSpeed: 1.9,
      pounceSpeed: 2.6,
      turnRate: 3.2,
      sightRange: 7.2,
      sightHalfAngle: 0.7,
      peripheralRange: 2.4,
      hearingRange: 6.5,
      scentSensitivity: 0.72,
      suspicionGain: 0.55,
      suspicionDecay: 0.22,
      memorySeconds: 6.5,
      pounceRange: 1.6,
      pounceCooldown: 2.8,
      searchSeconds: 5.5,
      napChance: 0.08,
    },
    weights: { patrol: 0.34, ambush: 0.18, camp: 0.16, wander: 0.24, nap: 0.08 },
  },
  {
    id: 'siamese',
    name: 'Siamese',
    blurb: 'Vocal sprinter. Hears a crumb drop two rooms away and arrives before the echo dies.',
    color: '#e8d8c8',
    stats: {
      patrolSpeed: 1.4,
      investigateSpeed: 1.85,
      chaseSpeed: 2.35,
      pounceSpeed: 2.9,
      turnRate: 4.4,
      sightRange: 8.1,
      sightHalfAngle: 0.62,
      peripheralRange: 2.1,
      hearingRange: 9.4,
      scentSensitivity: 0.4,
      suspicionGain: 0.7,
      suspicionDecay: 0.18,
      memorySeconds: 4.8,
      pounceRange: 1.45,
      pounceCooldown: 2.1,
      searchSeconds: 4.2,
      napChance: 0.02,
    },
    weights: { patrol: 0.22, ambush: 0.12, camp: 0.1, wander: 0.52, nap: 0.04 },
  },
  {
    id: 'persian',
    name: 'Persian',
    blurb: 'A velvet boulder parked on the hole. Slow to rise, slower to forgive, and extremely hard to sneak past twice.',
    color: '#f0e0c8',
    stats: {
      patrolSpeed: 0.72,
      investigateSpeed: 0.95,
      chaseSpeed: 1.35,
      pounceSpeed: 2.1,
      turnRate: 2.1,
      sightRange: 5.4,
      sightHalfAngle: 0.85,
      peripheralRange: 2.8,
      hearingRange: 4.2,
      scentSensitivity: 0.5,
      suspicionGain: 0.35,
      suspicionDecay: 0.12,
      memorySeconds: 9.5,
      pounceRange: 1.35,
      pounceCooldown: 3.6,
      searchSeconds: 7.8,
      napChance: 0.36,
    },
    weights: { patrol: 0.12, ambush: 0.14, camp: 0.46, wander: 0.08, nap: 0.2 },
  },
  {
    id: 'bengal',
    name: 'Bengal',
    blurb: 'Spots, stripes, and a personal vendetta against anything that scurries. Ambush first, ask never.',
    color: '#d4a03a',
    stats: {
      patrolSpeed: 1.35,
      investigateSpeed: 1.7,
      chaseSpeed: 2.5,
      pounceSpeed: 3.4,
      turnRate: 4.8,
      sightRange: 9.2,
      sightHalfAngle: 0.55,
      peripheralRange: 1.8,
      hearingRange: 7.1,
      scentSensitivity: 0.62,
      suspicionGain: 0.82,
      suspicionDecay: 0.14,
      memorySeconds: 5.2,
      pounceRange: 2.05,
      pounceCooldown: 1.7,
      searchSeconds: 3.8,
      napChance: 0.01,
    },
    weights: { patrol: 0.16, ambush: 0.42, camp: 0.1, wander: 0.3, nap: 0.02 },
  },
  {
    id: 'ragdoll',
    name: 'Ragdoll',
    blurb: 'Looks stuffed until you step on a creaky board. Then the whole rag stands up and remembers it has teeth.',
    color: '#c8b8d4',
    stats: {
      patrolSpeed: 0.85,
      investigateSpeed: 1.1,
      chaseSpeed: 1.7,
      pounceSpeed: 2.4,
      turnRate: 2.4,
      sightRange: 6.2,
      sightHalfAngle: 0.78,
      peripheralRange: 2.6,
      hearingRange: 5.5,
      scentSensitivity: 0.48,
      suspicionGain: 0.32,
      suspicionDecay: 0.28,
      memorySeconds: 7.2,
      pounceRange: 1.5,
      pounceCooldown: 3.2,
      searchSeconds: 6.4,
      napChance: 0.44,
    },
    weights: { patrol: 0.14, ambush: 0.1, camp: 0.22, wander: 0.16, nap: 0.38 },
  },
  {
    id: 'sphynx',
    name: 'Sphynx',
    blurb: 'No fur, all nose. Follows yesterday\'s footprints like a ledger and hates scented decoys on principle.',
    color: '#e8c4a8',
    stats: {
      patrolSpeed: 1.2,
      investigateSpeed: 1.55,
      chaseSpeed: 1.95,
      pounceSpeed: 2.55,
      turnRate: 3.6,
      sightRange: 4.6,
      sightHalfAngle: 0.9,
      peripheralRange: 3.1,
      hearingRange: 5.2,
      scentSensitivity: 1.25,
      suspicionGain: 0.6,
      suspicionDecay: 0.16,
      memorySeconds: 8.4,
      pounceRange: 1.4,
      pounceCooldown: 2.5,
      searchSeconds: 6.8,
      napChance: 0.05,
    },
    weights: { patrol: 0.28, ambush: 0.16, camp: 0.18, wander: 0.32, nap: 0.06 },
  },
  {
    id: 'maineCoon',
    name: 'Maine Coon',
    blurb: 'A door with whiskers. Sees across galleries, turns like a barge, and occupies whatever corridor you needed.',
    color: '#8a6038',
    stats: {
      patrolSpeed: 1.05,
      investigateSpeed: 1.25,
      chaseSpeed: 1.75,
      pounceSpeed: 2.35,
      turnRate: 2.05,
      sightRange: 11.4,
      sightHalfAngle: 0.5,
      peripheralRange: 2.2,
      hearingRange: 6.8,
      scentSensitivity: 0.58,
      suspicionGain: 0.48,
      suspicionDecay: 0.2,
      memorySeconds: 7.6,
      pounceRange: 1.85,
      pounceCooldown: 3.0,
      searchSeconds: 5.8,
      napChance: 0.1,
    },
    weights: { patrol: 0.46, ambush: 0.12, camp: 0.2, wander: 0.14, nap: 0.08 },
  },
  {
    id: 'scottishFold',
    name: 'Scottish Fold',
    blurb: 'Sits still enough to be furniture, then unfolds into a pounce from the shadow of a chair leg.',
    color: '#c8b090',
    stats: {
      patrolSpeed: 0.9,
      investigateSpeed: 1.2,
      chaseSpeed: 1.85,
      pounceSpeed: 3.15,
      turnRate: 3.8,
      sightRange: 6.4,
      sightHalfAngle: 0.68,
      peripheralRange: 2.0,
      hearingRange: 8.2,
      scentSensitivity: 0.64,
      suspicionGain: 0.5,
      suspicionDecay: 0.1,
      memorySeconds: 6.0,
      pounceRange: 2.2,
      pounceCooldown: 2.4,
      searchSeconds: 4.6,
      napChance: 0.14,
    },
    weights: { patrol: 0.1, ambush: 0.48, camp: 0.22, wander: 0.1, nap: 0.1 },
  },
  {
    id: 'bombay',
    name: 'Bombay',
    blurb: 'A hole in the dark that listens. Sight is optional; the click of a toenail is not.',
    color: '#1a1214',
    stats: {
      patrolSpeed: 1.18,
      investigateSpeed: 1.6,
      chaseSpeed: 2.15,
      pounceSpeed: 2.85,
      turnRate: 3.9,
      sightRange: 5.1,
      sightHalfAngle: 0.95,
      peripheralRange: 3.4,
      hearingRange: 10.6,
      scentSensitivity: 0.7,
      suspicionGain: 0.66,
      suspicionDecay: 0.15,
      memorySeconds: 5.6,
      pounceRange: 1.55,
      pounceCooldown: 2.2,
      searchSeconds: 5.0,
      napChance: 0.06,
    },
    weights: { patrol: 0.24, ambush: 0.28, camp: 0.14, wander: 0.28, nap: 0.06 },
  },
  {
    id: 'calico',
    name: 'Calico',
    blurb: 'Three cats in a trench coat of fur. Patrol, nap, and ambush all argue, and you never know who won.',
    color: '#e8a050',
    stats: {
      patrolSpeed: 1.08,
      investigateSpeed: 1.5,
      chaseSpeed: 2.05,
      pounceSpeed: 2.7,
      turnRate: 3.5,
      sightRange: 7.0,
      sightHalfAngle: 0.72,
      peripheralRange: 2.5,
      hearingRange: 6.9,
      scentSensitivity: 0.8,
      suspicionGain: 0.58,
      suspicionDecay: 0.24,
      memorySeconds: 6.8,
      pounceRange: 1.6,
      pounceCooldown: 2.6,
      searchSeconds: 5.2,
      napChance: 0.16,
    },
    weights: { patrol: 0.2, ambush: 0.22, camp: 0.14, wander: 0.3, nap: 0.14 },
  },
  {
    id: 'norwegianForest',
    name: 'Norwegian Forest',
    blurb: 'Outdoor patrol routes burned into muscle memory. Treats indoor hallways like game trails.',
    color: '#6a4a32',
    stats: {
      patrolSpeed: 1.28,
      investigateSpeed: 1.42,
      chaseSpeed: 1.88,
      pounceSpeed: 2.5,
      turnRate: 2.7,
      sightRange: 8.4,
      sightHalfAngle: 0.6,
      peripheralRange: 2.3,
      hearingRange: 7.4,
      scentSensitivity: 0.92,
      suspicionGain: 0.44,
      suspicionDecay: 0.19,
      memorySeconds: 8.8,
      pounceRange: 1.7,
      pounceCooldown: 2.9,
      searchSeconds: 6.1,
      napChance: 0.07,
    },
    weights: { patrol: 0.5, ambush: 0.14, camp: 0.12, wander: 0.18, nap: 0.06 },
  },
  {
    id: 'abyssinian',
    name: 'Abyssinian',
    blurb: 'Curious to a fault. Every closed door is a mystery, every missing crumb a case file.',
    color: '#c87838',
    stats: {
      patrolSpeed: 1.22,
      investigateSpeed: 2.05,
      chaseSpeed: 2.1,
      pounceSpeed: 2.65,
      turnRate: 4.1,
      sightRange: 8.0,
      sightHalfAngle: 0.66,
      peripheralRange: 2.7,
      hearingRange: 8.0,
      scentSensitivity: 0.76,
      suspicionGain: 0.74,
      suspicionDecay: 0.3,
      memorySeconds: 4.4,
      pounceRange: 1.5,
      pounceCooldown: 2.0,
      searchSeconds: 7.4,
      napChance: 0.04,
    },
    weights: { patrol: 0.18, ambush: 0.16, camp: 0.08, wander: 0.54, nap: 0.04 },
  },
  {
    id: 'britishShorthair',
    name: 'British Shorthair',
    blurb: 'Assigned to the hole. Considers leaving it a dereliction of duty and napping on it a promotion.',
    color: '#9aa4b0',
    stats: {
      patrolSpeed: 0.95,
      investigateSpeed: 1.15,
      chaseSpeed: 1.6,
      pounceSpeed: 2.3,
      turnRate: 2.6,
      sightRange: 6.6,
      sightHalfAngle: 0.8,
      peripheralRange: 2.9,
      hearingRange: 5.4,
      scentSensitivity: 0.52,
      suspicionGain: 0.4,
      suspicionDecay: 0.14,
      memorySeconds: 10.2,
      pounceRange: 1.45,
      pounceCooldown: 3.4,
      searchSeconds: 4.8,
      napChance: 0.18,
    },
    weights: { patrol: 0.16, ambush: 0.12, camp: 0.52, wander: 0.08, nap: 0.12 },
  },
  {
    id: 'russianBlue',
    name: 'Russian Blue',
    blurb: 'A rumour with paws. Stalks the long way around, then occupies the one tile you needed to breathe.',
    color: '#7a8a98',
    stats: {
      patrolSpeed: 1.12,
      investigateSpeed: 1.48,
      chaseSpeed: 2.0,
      pounceSpeed: 2.95,
      turnRate: 3.3,
      sightRange: 9.0,
      sightHalfAngle: 0.48,
      peripheralRange: 1.6,
      hearingRange: 4.6,
      scentSensitivity: 0.38,
      suspicionGain: 0.52,
      suspicionDecay: 0.08,
      memorySeconds: 7.0,
      pounceRange: 1.9,
      pounceCooldown: 2.7,
      searchSeconds: 5.4,
      napChance: 0.07,
    },
    weights: { patrol: 0.2, ambush: 0.44, camp: 0.16, wander: 0.14, nap: 0.06 },
  },
  {
    id: 'savannah',
    name: 'Savannah',
    blurb: 'Long legs, longer sightlines. Treats open floors as savannah and furniture as disappointing tall grass.',
    color: '#d4b46a',
    stats: {
      patrolSpeed: 1.45,
      investigateSpeed: 1.65,
      chaseSpeed: 2.28,
      pounceSpeed: 3.05,
      turnRate: 3.0,
      sightRange: 12.2,
      sightHalfAngle: 0.42,
      peripheralRange: 1.9,
      hearingRange: 7.8,
      scentSensitivity: 0.66,
      suspicionGain: 0.6,
      suspicionDecay: 0.21,
      memorySeconds: 5.8,
      pounceRange: 2.15,
      pounceCooldown: 2.3,
      searchSeconds: 4.4,
      napChance: 0.03,
    },
    weights: { patrol: 0.36, ambush: 0.22, camp: 0.08, wander: 0.3, nap: 0.04 },
  },
  {
    id: 'manx',
    name: 'Manx',
    blurb: 'No tail, all spring. Short patrols, sudden lunges, and a habit of cutting corners you thought were yours.',
    color: '#b07848',
    stats: {
      patrolSpeed: 1.1,
      investigateSpeed: 1.52,
      chaseSpeed: 2.22,
      pounceSpeed: 3.35,
      turnRate: 5.1,
      sightRange: 6.0,
      sightHalfAngle: 0.74,
      peripheralRange: 2.2,
      hearingRange: 6.2,
      scentSensitivity: 0.54,
      suspicionGain: 0.68,
      suspicionDecay: 0.26,
      memorySeconds: 3.9,
      pounceRange: 2.35,
      pounceCooldown: 1.5,
      searchSeconds: 3.6,
      napChance: 0.09,
    },
    weights: { patrol: 0.18, ambush: 0.36, camp: 0.12, wander: 0.26, nap: 0.08 },
  },
];

export const BREED_BY_ID: Readonly<Record<string, BreedDef>> = Object.fromEntries(
  BREEDS.map((breed) => [breed.id, breed]),
);

export const STARTER_BREED_ID = 'tabby';

export const BREED_IDS: readonly string[] = BREEDS.map((breed) => breed.id);
