import type { HazardKind, PowerUpKind } from '../game/types';
import type { ThemeId, TileGlyph } from './schema';

export interface ThemeKit {
  readonly id: ThemeId;
  readonly floor: TileGlyph;
  readonly altFloor: TileGlyph;
  readonly clutter: readonly TileGlyph[];
  readonly liquid: TileGlyph | null;
  readonly vertical: TileGlyph | null;
  readonly hazards: readonly HazardKind[];
  readonly powerUps: readonly PowerUpKind[];
  readonly landmarks: readonly string[];
  readonly breeds: readonly string[];
  readonly music: string;
  readonly ambient: number;
}

export const THEME_KITS: Readonly<Record<ThemeId, ThemeKit>> = {
  cellar: {
    id: 'cellar',
    floor: '.',
    altFloor: 'r',
    clutter: ['X', 'T', 's'],
    liquid: '~',
    vertical: 's',
    hazards: ['snapTrap', 'sparkWire', 'glueBoard'],
    powerUps: ['scentMask', 'featherFoot', 'noiseBomb'],
    landmarks: ['wine rack', 'coal chute', 'furnace door', 'jar wall', 'hatch'],
    breeds: ['persian', 'ragdoll', 'tabby', 'britishShorthair'],
    music: 'cellar-drip',
    ambient: 0.28,
  },
  kitchen: {
    id: 'kitchen',
    floor: '.',
    altFloor: 'r',
    clutter: ['T', 'X', 'r'],
    liquid: '~',
    vertical: null,
    hazards: ['snapTrap', 'glueBoard', 'broom'],
    powerUps: ['speed', 'decoy', 'magnet'],
    landmarks: ['fridge', 'sink island', 'oven', 'spice rack', 'breadbox'],
    breeds: ['tabby', 'calico', 'ragdoll', 'scottishFold'],
    music: 'kitchen-night',
    ambient: 0.62,
  },
  alley: {
    id: 'alley',
    floor: '.',
    altFloor: 'g',
    clutter: ['X', 'G', 'p'],
    liquid: '~',
    vertical: 's',
    hazards: ['glueBoard', 'broom', 'fan'],
    powerUps: ['noiseBomb', 'speed', 'invisibility'],
    landmarks: ['dumpster', 'fire escape', 'neon sign', 'loading dock', 'chain fence'],
    breeds: ['bombay', 'siamese', 'bengal', 'calico'],
    music: 'alley-neon',
    ambient: 0.34,
  },
  sewer: {
    id: 'sewer',
    floor: '.',
    altFloor: 'g',
    clutter: ['p', 'g', 'X'],
    liquid: '~',
    vertical: 'p',
    hazards: ['water', 'fan', 'sparkWire'],
    powerUps: ['featherFoot', 'scentMask', 'timeSlip'],
    landmarks: ['overflow gate', 'pump', 'outflow', 'echo bend', 'grate well'],
    breeds: ['sphynx', 'norwegianForest', 'bombay', 'manx'],
    music: 'sewer-flow',
    ambient: 0.3,
  },
  attic: {
    id: 'attic',
    floor: '.',
    altFloor: 'r',
    clutter: ['X', 'L', 'v'],
    liquid: null,
    vertical: 'L',
    hazards: ['snapTrap', 'glueBoard', 'broom'],
    powerUps: ['invisibility', 'featherFoot', 'decoy'],
    landmarks: ['steamer trunk', 'dormer', 'chimney', 'hatbox stack', 'widow walk'],
    breeds: ['ragdoll', 'scottishFold', 'russianBlue', 'tabby'],
    music: 'attic-moths',
    ambient: 0.4,
  },
  carnival: {
    id: 'carnival',
    floor: '.',
    altFloor: 'r',
    clutter: ['T', 'G', 'X'],
    liquid: null,
    vertical: 's',
    hazards: ['broom', 'fan', 'glueBoard'],
    powerUps: ['speed', 'decoy', 'noiseBomb'],
    landmarks: ['ticket booth', 'bumper floor', 'mirror hall', 'prize tent', 'ferris shadow'],
    breeds: ['bengal', 'siamese', 'calico', 'manx'],
    music: 'carnival-closed',
    ambient: 0.48,
  },
  museum: {
    id: 'museum',
    floor: '.',
    altFloor: 'r',
    clutter: ['T', 'G', 's'],
    liquid: null,
    vertical: 's',
    hazards: ['glueBoard', 'snapTrap', 'sparkWire'],
    powerUps: ['scentMask', 'invisibility', 'timeSlip'],
    landmarks: ['marble foyer', 'armor hall', 'vase wing', 'fossil pit', 'archive vault'],
    breeds: ['maineCoon', 'britishShorthair', 'russianBlue', 'persian'],
    music: 'museum-echo',
    ambient: 0.55,
  },
  subway: {
    id: 'subway',
    floor: '.',
    altFloor: 'g',
    clutter: ['p', 's', 'X'],
    liquid: null,
    vertical: 's',
    hazards: ['sparkWire', 'fan', 'vacuum'],
    powerUps: ['speed', 'noiseBomb', 'magnet'],
    landmarks: ['platform edge', 'turnstile', 'map kiosk', 'third rail', 'lost and found'],
    breeds: ['bombay', 'savannah', 'siamese', 'abyssinian'],
    music: 'subway-last',
    ambient: 0.36,
  },
  docks: {
    id: 'docks',
    floor: '.',
    altFloor: 'L',
    clutter: ['X', 'p', 'L'],
    liquid: '~',
    vertical: 'L',
    hazards: ['water', 'fan', 'glueBoard'],
    powerUps: ['featherFoot', 'magnet', 'extraLife'],
    landmarks: ['pier', 'net loft', 'gangway', 'cold storage', 'captain cabin'],
    breeds: ['norwegianForest', 'maineCoon', 'sphynx', 'tabby'],
    music: 'docks-foghorn',
    ambient: 0.32,
  },
  greenhouse: {
    id: 'greenhouse',
    floor: '.',
    altFloor: 'r',
    clutter: ['T', 'G', 'X'],
    liquid: '~',
    vertical: null,
    hazards: ['water', 'glueBoard', 'fan'],
    powerUps: ['scentMask', 'magnet', 'decoy'],
    landmarks: ['seedling row', 'mist house', 'orchid maze', 'compost', 'queen agave'],
    breeds: ['abyssinian', 'sphynx', 'calico', 'scottishFold'],
    music: 'greenhouse-hum',
    ambient: 0.5,
  },
  clocktower: {
    id: 'clocktower',
    floor: '.',
    altFloor: 's',
    clutter: ['L', 'g', 'p'],
    liquid: null,
    vertical: 's',
    hazards: ['sparkWire', 'fan', 'snapTrap'],
    powerUps: ['timeSlip', 'featherFoot', 'freeze'],
    landmarks: ['gear floor', 'pendulum well', 'bell loft', 'escapement', 'face scaffold'],
    breeds: ['savannah', 'russianBlue', 'maineCoon', 'manx'],
    music: 'clocktower-tick',
    ambient: 0.38,
  },
  moonLab: {
    id: 'moonLab',
    floor: '.',
    altFloor: 'G',
    clutter: ['G', 'v', 'D'],
    liquid: null,
    vertical: 'v',
    hazards: ['sparkWire', 'vacuum', 'fan'],
    powerUps: ['freeze', 'invisibility', 'extraLife'],
    landmarks: ['airlock', 'sample vault', 'centrifuge', 'cryo bay', 'launch cradle'],
    breeds: ['savannah', 'bengal', 'siamese', 'britishShorthair'],
    music: 'moonlab-protocol',
    ambient: 0.7,
  },
};
