-- quality-qms 0001: schema, number series, inspection plans
--
-- Conventions (all quality-qms migrations):
--  * schema `quality`
--  * ids are prefixed string ULIDs (TEXT), generated by the application
--  * every table carries tenant_id; all natural-key uniques are per tenant
--  * enums are TEXT + CHECK constraints (easier to evolve than PG enums)
--  * timestamps are TIMESTAMPTZ, application-supplied ISO instants

CREATE SCHEMA IF NOT EXISTS quality;

-- Tenant-scoped document numbering (NCR-2026-000001, ...). Sequences
-- restart per year; `next` advances under row lock.
CREATE TABLE quality.number_series (
    tenant_id     TEXT        NOT NULL,
    series_code   TEXT        NOT NULL,
    year          INTEGER     NOT NULL,
    last_value    INTEGER     NOT NULL DEFAULT 0,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, series_code, year)
);

CREATE TABLE quality.inspection_plan (
    id             TEXT        PRIMARY KEY,
    tenant_id      TEXT        NOT NULL,
    plan_code      TEXT        NOT NULL,
    name           TEXT        NOT NULL,
    description    TEXT,
    target_type    TEXT        NOT NULL CHECK (target_type IN ('material', 'product', 'process')),
    material_code  TEXT,
    revision       INTEGER     NOT NULL DEFAULT 1,
    status         TEXT        NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'retired')),
    -- lot origins this plan may serve; empty array means "any origin"
    allowed_origins TEXT[]     NOT NULL DEFAULT '{}',
    -- sampling rule discriminated union, e.g.
    --   {"kind":"aql","level":"II","aql":1.0} | {"kind":"fixed","sampleSize":5}
    sampling_rule  JSONB       NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ NOT NULL,
    version        INTEGER     NOT NULL DEFAULT 1,
    CONSTRAINT inspection_plan_code_rev_uq UNIQUE (tenant_id, plan_code, revision),
    CONSTRAINT inspection_plan_material_required CHECK (
        target_type = 'process' OR material_code IS NOT NULL
    )
);

-- At most one ACTIVE revision per plan code and tenant.
CREATE UNIQUE INDEX inspection_plan_one_active_uq
    ON quality.inspection_plan (tenant_id, plan_code)
    WHERE status = 'active';

CREATE INDEX inspection_plan_material_ix
    ON quality.inspection_plan (tenant_id, material_code)
    WHERE status = 'active';

CREATE TABLE quality.inspection_plan_characteristic (
    id                    TEXT        PRIMARY KEY,
    tenant_id             TEXT        NOT NULL,
    plan_id               TEXT        NOT NULL REFERENCES quality.inspection_plan (id) ON DELETE CASCADE,
    code                  TEXT        NOT NULL,
    name                  TEXT        NOT NULL,
    char_type             TEXT        NOT NULL CHECK (char_type IN ('quantitative', 'attribute')),
    criticality           TEXT        NOT NULL CHECK (criticality IN ('critical', 'major', 'minor')),
    method                TEXT,
    -- quantitative spec (NULL for attribute characteristics)
    unit                  TEXT,
    target_value          NUMERIC,
    lower_limit           NUMERIC,
    upper_limit           NUMERIC,
    decimals              INTEGER,
    sample_size_override  INTEGER CHECK (sample_size_override IS NULL OR sample_size_override >= 1),
    position              INTEGER     NOT NULL DEFAULT 0,
    CONSTRAINT plan_characteristic_code_uq UNIQUE (plan_id, code),
    CONSTRAINT quantitative_needs_unit CHECK (
        char_type <> 'quantitative' OR unit IS NOT NULL
    ),
    CONSTRAINT quantitative_needs_a_limit CHECK (
        char_type <> 'quantitative'
        OR lower_limit IS NOT NULL OR upper_limit IS NOT NULL OR target_value IS NOT NULL
    ),
    CONSTRAINT limits_ordered CHECK (
        lower_limit IS NULL OR upper_limit IS NULL OR lower_limit < upper_limit
    )
);

CREATE INDEX plan_characteristic_plan_ix
    ON quality.inspection_plan_characteristic (plan_id);

COMMENT ON TABLE quality.inspection_plan IS
    'Versioned inspection plans; lots snapshot characteristics at creation';
COMMENT ON COLUMN quality.inspection_plan.sampling_rule IS
    'Discriminated union: full | fixed | percentage | aql (ISO 2859-1 single normal)';
