import { RouteTable } from "../domain/route-table.js";
import type { HttpMethod, RateLimitPolicy, RouteAuth, RouteDefinition } from "../domain/route.js";
import type { ServiceCatalog } from "../domain/service-catalog.js";

/**
 * The reference route table.
 *
 * Rather than hand-writing five near-identical entries per resource, the
 * standard read/write surface is generated by {@link resourceRoutes} and the
 * genuinely interesting operations (state transitions, reports, bulk jobs) are
 * declared explicitly. Every entry still carries its own auth mode, rate
 * limit and tags, so nothing is lost to the shorthand.
 */

const READ_LIMIT: RateLimitPolicy = { limit: 600, windowMs: 60_000, key: "tenant" };
const WRITE_LIMIT: RateLimitPolicy = { limit: 120, windowMs: 60_000, key: "tenant-user" };
const HEAVY_LIMIT: RateLimitPolicy = { limit: 20, windowMs: 60_000, key: "tenant" };

export interface ResourceRoutesInput {
  readonly service: string;
  readonly prefix: string;
  /** Collection path relative to the prefix, e.g. `products`. */
  readonly resource: string;
  readonly idParam?: string;
  readonly readRoles?: readonly string[];
  readonly writeRoles?: readonly string[];
  readonly readPermission?: string;
  readonly writePermission?: string;
  readonly operations?: readonly ("list" | "get" | "create" | "update" | "delete")[];
  readonly tags?: readonly string[];
}

function auth(roles: readonly string[] | undefined, permission?: string): RouteAuth {
  if (!roles || roles.length === 0) {
    return permission ? { mode: "tenant", allOfPermissions: [permission] } : { mode: "tenant" };
  }
  return {
    mode: "roles",
    anyOfRoles: roles,
    allOfPermissions: permission ? [permission] : undefined,
  };
}

export function resourceRoutes(input: ResourceRoutesInput): RouteDefinition[] {
  const idParam = input.idParam ?? "id";
  const base = `${input.prefix}/${input.resource}`;
  const item = `${base}/:${idParam}`;
  const tags = input.tags ?? [input.resource];
  const operations = input.operations ?? ["list", "get", "create", "update", "delete"];
  const readAuth = auth(input.readRoles, input.readPermission);
  const writeAuth = auth(input.writeRoles, input.writePermission);

  const all: Record<string, RouteDefinition> = {
    list: {
      id: `${input.service}.${input.resource}.list`,
      method: "GET",
      pattern: base,
      upstream: input.service,
      auth: readAuth,
      rateLimit: READ_LIMIT,
      summary: `List ${input.resource}`,
      tags,
      idempotent: true,
    },
    get: {
      id: `${input.service}.${input.resource}.get`,
      method: "GET",
      pattern: item,
      upstream: input.service,
      auth: readAuth,
      rateLimit: READ_LIMIT,
      summary: `Fetch one ${singular(input.resource)}`,
      tags,
      idempotent: true,
    },
    create: {
      id: `${input.service}.${input.resource}.create`,
      method: "POST",
      pattern: base,
      upstream: input.service,
      auth: writeAuth,
      rateLimit: WRITE_LIMIT,
      summary: `Create a ${singular(input.resource)}`,
      tags,
    },
    update: {
      id: `${input.service}.${input.resource}.update`,
      method: "PATCH",
      pattern: item,
      upstream: input.service,
      auth: writeAuth,
      rateLimit: WRITE_LIMIT,
      summary: `Update a ${singular(input.resource)}`,
      tags,
    },
    delete: {
      id: `${input.service}.${input.resource}.delete`,
      method: "DELETE",
      pattern: item,
      upstream: input.service,
      auth: writeAuth,
      rateLimit: WRITE_LIMIT,
      summary: `Delete a ${singular(input.resource)}`,
      tags,
    },
  };

  return operations.map((operation) => all[operation]!);
}

export interface ActionRouteInput {
  readonly service: string;
  readonly method: HttpMethod;
  readonly pattern: string;
  readonly id: string;
  readonly summary: string;
  readonly auth?: RouteAuth;
  readonly roles?: readonly string[];
  readonly permission?: string;
  readonly rateLimit?: RateLimitPolicy;
  readonly tags?: readonly string[];
  readonly rewrite?: string;
  readonly timeoutMs?: number;
}

export function actionRoute(input: ActionRouteInput): RouteDefinition {
  return {
    id: input.id,
    method: input.method,
    pattern: input.pattern,
    upstream: input.service,
    auth: input.auth ?? auth(input.roles, input.permission),
    rateLimit: input.rateLimit ?? WRITE_LIMIT,
    summary: input.summary,
    tags: input.tags,
    rewrite: input.rewrite,
    timeoutMs: input.timeoutMs,
  };
}

const SALES = "/api/sales";
const PLM = "/api/plm";
const INVENTORY = "/api/inventory";
const FINANCE = "/api/finance";
const QUALITY = "/api/quality";
const ADMIN = "/api/admin";
const IAM = "/api/iam";
const SRM = "/api/srm";
const PROCUREMENT = "/api/procurement";
const PRM = "/api/prm";
const INTEGRATION = "/api/integration";
const REPORTING = "/api/reporting";

/** Every route the reference gateway serves. */
export function buildRouteDefinitions(): RouteDefinition[] {
  const routes: RouteDefinition[] = [];

  // ---- Sales -------------------------------------------------------------
  routes.push(
    ...resourceRoutes({
      service: "sales-erp",
      prefix: SALES,
      resource: "quotes",
      readRoles: ["sales-rep", "sales-manager", "tenant-admin", "auditor"],
      writeRoles: ["sales-rep", "sales-manager", "tenant-admin"],
      operations: ["list", "get", "create"],
    }),
    ...resourceRoutes({
      service: "sales-erp",
      prefix: SALES,
      resource: "orders",
      readRoles: ["sales-rep", "sales-manager", "tenant-admin", "auditor"],
      writeRoles: ["sales-manager", "tenant-admin"],
      operations: ["list", "get", "create"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.quotes.submit",
      method: "POST",
      pattern: `${SALES}/quotes/:quoteId/submit`,
      summary: "Submit a quote for approval",
      roles: ["sales-rep", "sales-manager"],
      tags: ["quotes"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.quotes.approve",
      method: "POST",
      pattern: `${SALES}/quotes/:quoteId/approve`,
      summary: "Approve a submitted quote",
      roles: ["sales-manager", "tenant-admin"],
      tags: ["quotes"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.quotes.reject",
      method: "POST",
      pattern: `${SALES}/quotes/:quoteId/reject`,
      summary: "Reject a submitted quote",
      roles: ["sales-manager", "tenant-admin"],
      tags: ["quotes"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.quotes.accept",
      method: "POST",
      pattern: `${SALES}/quotes/:quoteId/accept`,
      summary: "Accept a quote and create its sales order",
      roles: ["sales-rep", "sales-manager", "tenant-admin"],
      tags: ["quotes", "orders"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.quotes.cancel",
      method: "POST",
      pattern: `${SALES}/quotes/:quoteId/cancel`,
      summary: "Cancel a quote",
      roles: ["sales-rep", "sales-manager", "tenant-admin"],
      tags: ["quotes"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.quotes.lines.add",
      method: "POST",
      pattern: `${SALES}/quotes/:quoteId/lines`,
      summary: "Add a quote line",
      roles: ["sales-rep", "sales-manager", "tenant-admin"],
      tags: ["quotes"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.quotes.lines.update",
      method: "PATCH",
      pattern: `${SALES}/quotes/:quoteId/lines/:lineId`,
      summary: "Update a quote line",
      roles: ["sales-rep", "sales-manager", "tenant-admin"],
      tags: ["quotes"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.quotes.lines.delete",
      method: "DELETE",
      pattern: `${SALES}/quotes/:quoteId/lines/:lineId`,
      summary: "Remove a quote line",
      roles: ["sales-rep", "sales-manager", "tenant-admin"],
      tags: ["quotes"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.orders.from-quote",
      method: "POST",
      pattern: `${SALES}/orders/from-quote`,
      summary: "Create an order from an accepted quote",
      roles: ["sales-manager", "tenant-admin"],
      tags: ["quotes", "orders"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.orders.confirm",
      method: "POST",
      pattern: `${SALES}/orders/:orderId/confirm`,
      summary: "Confirm a sales order",
      roles: ["sales-manager", "tenant-admin"],
      tags: ["orders"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.orders.allocate",
      method: "POST",
      pattern: `${SALES}/orders/:orderId/allocate`,
      summary: "Allocate inventory to an order",
      roles: ["sales-manager", "tenant-admin"],
      tags: ["orders"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.orders.ship",
      method: "POST",
      pattern: `${SALES}/orders/:orderId/ship`,
      summary: "Record an order shipment",
      roles: ["sales-manager", "tenant-admin"],
      tags: ["orders"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.orders.invoice",
      method: "POST",
      pattern: `${SALES}/orders/:orderId/invoice`,
      summary: "Mark an order as invoiced",
      roles: ["sales-manager", "tenant-admin"],
      tags: ["orders"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.orders.close",
      method: "POST",
      pattern: `${SALES}/orders/:orderId/close`,
      summary: "Close a fulfilled order",
      roles: ["sales-manager", "tenant-admin"],
      tags: ["orders"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.orders.cancel",
      method: "POST",
      pattern: `${SALES}/orders/:orderId/cancel`,
      summary: "Cancel an order and release allocations",
      roles: ["sales-manager", "tenant-admin"],
      tags: ["orders"],
    }),
  );

  // ---- Product / PLM -----------------------------------------------------
  routes.push(
    ...resourceRoutes({
      service: "product-plm",
      prefix: PLM,
      resource: "products",
      idParam: "productId",
      writeRoles: ["product-manager", "tenant-admin"],
    }),
    ...resourceRoutes({
      service: "product-plm",
      prefix: PLM,
      resource: "ecos",
      idParam: "ecoId",
      writeRoles: ["product-manager", "tenant-admin"],
      operations: ["list", "get", "create"],
    }),
    actionRoute({
      service: "product-plm",
      id: "product-plm.products.bom",
      method: "GET",
      pattern: `${PLM}/products/:productId/bom`,
      summary: "Read the effective bill of materials",
      rateLimit: READ_LIMIT,
      tags: ["bom"],
    }),
    actionRoute({
      service: "product-plm",
      id: "product-plm.products.explosion",
      method: "GET",
      pattern: `${PLM}/products/:productId/bom/explosion`,
      summary: "Explode a BOM to component level",
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 30_000,
      tags: ["bom"],
    }),
    actionRoute({
      service: "product-plm",
      id: "product-plm.ecos.approve",
      method: "POST",
      pattern: `${PLM}/ecos/:ecoId/approve`,
      summary: "Approve an engineering change order",
      roles: ["product-manager", "tenant-admin"],
      tags: ["eco"],
    }),
  );

  // ---- Inventory ---------------------------------------------------------
  routes.push(
    ...resourceRoutes({
      service: "inventory-wms",
      prefix: INVENTORY,
      resource: "warehouses",
      writeRoles: ["inventory-manager", "tenant-admin"],
      operations: ["list", "get", "create", "update"],
    }),
    actionRoute({
      service: "inventory-wms",
      id: "inventory-wms.stock.query",
      method: "GET",
      pattern: `${INVENTORY}/stock`,
      summary: "Query on-hand and available stock",
      rateLimit: READ_LIMIT,
      tags: ["stock"],
    }),
    actionRoute({
      service: "inventory-wms",
      id: "inventory-wms.movements.post",
      method: "POST",
      pattern: `${INVENTORY}/movements`,
      summary: "Post a stock movement",
      roles: ["warehouse-operator", "inventory-manager", "tenant-admin"],
      tags: ["stock"],
    }),
    actionRoute({
      service: "inventory-wms",
      id: "inventory-wms.counts.reconcile",
      method: "POST",
      pattern: `${INVENTORY}/counts/:countId/reconcile`,
      summary: "Reconcile a cycle count",
      roles: ["inventory-manager", "tenant-admin"],
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 60_000,
      tags: ["stock"],
    }),
  );

  // ---- Finance -----------------------------------------------------------
  routes.push(
    ...resourceRoutes({
      service: "finance-erp",
      prefix: FINANCE,
      resource: "journals",
      readRoles: ["accountant", "controller", "auditor", "tenant-admin"],
      writeRoles: ["accountant", "controller"],
      operations: ["list", "get", "create"],
    }),
    ...resourceRoutes({
      service: "finance-erp",
      prefix: FINANCE,
      resource: "ar/invoices",
      idParam: "invoiceId",
      readRoles: ["accountant", "controller", "auditor", "tenant-admin"],
      writeRoles: ["accountant", "controller"],
      operations: ["list", "get", "create"],
      tags: ["accounts-receivable"],
    }),
    ...resourceRoutes({
      service: "finance-erp",
      prefix: FINANCE,
      resource: "ap/bills",
      idParam: "billId",
      readRoles: ["accountant", "controller", "auditor", "tenant-admin"],
      writeRoles: ["accountant", "controller"],
      operations: ["list", "get", "create"],
      tags: ["accounts-payable"],
    }),
    actionRoute({
      service: "finance-erp",
      id: "finance-erp.journals.post",
      method: "POST",
      pattern: `${FINANCE}/journals/:journalId/post`,
      summary: "Post a journal",
      roles: ["accountant", "controller"],
      tags: ["gl"],
    }),
    actionRoute({
      service: "finance-erp",
      id: "finance-erp.journals.reverse",
      method: "POST",
      pattern: `${FINANCE}/journals/:journalId/reverse`,
      summary: "Reverse a posted journal",
      roles: ["accountant", "controller"],
      tags: ["gl"],
    }),
    actionRoute({
      service: "finance-erp",
      id: "finance-erp.periods.close.begin",
      method: "POST",
      pattern: `${FINANCE}/periods/:periodCode/close/begin`,
      summary: "Begin an accounting period close",
      roles: ["controller"],
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 120_000,
      tags: ["gl"],
    }),
    actionRoute({
      service: "finance-erp",
      id: "finance-erp.periods.close.check",
      method: "POST",
      pattern: `${FINANCE}/periods/:periodCode/close/run-checks`,
      summary: "Run accounting period close checks",
      roles: ["controller"],
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 120_000,
      tags: ["gl"],
    }),
    actionRoute({
      service: "finance-erp",
      id: "finance-erp.periods.close.complete",
      method: "POST",
      pattern: `${FINANCE}/periods/:periodCode/close/complete`,
      summary: "Complete an accounting period close",
      roles: ["controller"],
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 120_000,
      tags: ["gl"],
    }),
    actionRoute({
      service: "finance-erp",
      id: "finance-erp.ar-invoices.issue",
      method: "POST",
      pattern: `${FINANCE}/ar/invoices/:invoiceId/issue`,
      summary: "Issue an accounts-receivable invoice",
      roles: ["accountant", "controller"],
      tags: ["accounts-receivable"],
    }),
    actionRoute({
      service: "finance-erp",
      id: "finance-erp.ar-invoices.void",
      method: "POST",
      pattern: `${FINANCE}/ar/invoices/:invoiceId/void`,
      summary: "Void an accounts-receivable invoice",
      roles: ["accountant", "controller"],
      tags: ["accounts-receivable"],
    }),
    actionRoute({
      service: "finance-erp",
      id: "finance-erp.ap-bills.approve",
      method: "POST",
      pattern: `${FINANCE}/ap/bills/:billId/approve`,
      summary: "Approve an accounts-payable bill",
      roles: ["accountant", "controller"],
      tags: ["accounts-payable"],
    }),
    actionRoute({
      service: "finance-erp",
      id: "finance-erp.reports.trial-balance",
      method: "GET",
      pattern: `${FINANCE}/reports/trial-balance`,
      summary: "Trial balance for a period",
      roles: ["accountant", "controller", "auditor"],
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 30_000,
      tags: ["reports"],
    }),
  );

  // ---- Quality -----------------------------------------------------------
  routes.push(
    ...resourceRoutes({
      service: "quality-qms",
      prefix: QUALITY,
      resource: "ncrs",
      writeRoles: ["quality-inspector", "quality-manager", "tenant-admin"],
      operations: ["list", "get", "create", "update"],
    }),
    ...resourceRoutes({
      service: "quality-qms",
      prefix: QUALITY,
      resource: "capas",
      writeRoles: ["quality-manager", "tenant-admin"],
      operations: ["list", "get", "create", "update"],
    }),
    actionRoute({
      service: "quality-qms",
      id: "quality-qms.inspections.record",
      method: "POST",
      pattern: `${QUALITY}/inspections/:inspectionId/results`,
      summary: "Record inspection results",
      roles: ["quality-inspector", "quality-manager"],
      tags: ["inspections"],
    }),
  );

  // ---- Remaining ERP contexts (standard surface) -------------------------
  routes.push(
    ...resourceRoutes({ service: "marketing-erp", prefix: "/api/marketing", resource: "campaigns", writeRoles: ["marketing-manager", "tenant-admin"] }),
    ...resourceRoutes({ service: "marketing-erp", prefix: "/api/marketing", resource: "leads", writeRoles: ["marketing-manager", "sales-rep", "tenant-admin"], operations: ["list", "get", "create", "update"] }),
    ...resourceRoutes({ service: "supply-chain", prefix: "/api/scm", resource: "plans", writeRoles: ["planner", "tenant-admin"], operations: ["list", "get", "create"] }),
    ...resourceRoutes({ service: "manufacturing-mes", prefix: "/api/mes", resource: "work-orders", writeRoles: ["production-supervisor", "tenant-admin"], operations: ["list", "get", "create"] }),
    ...resourceRoutes({ service: "hcm-erp", prefix: "/api/hcm", resource: "employees", readRoles: ["hr-specialist", "hr-manager", "tenant-admin"], writeRoles: ["hr-manager", "tenant-admin"] }),
    ...resourceRoutes({ service: "logistics-tms", prefix: "/api/logistics", resource: "shipments", writeRoles: ["logistics-coordinator", "tenant-admin"], operations: ["list", "get", "create", "update"] }),
    actionRoute({
      service: "supply-chain",
      id: "supply-chain.mrp.run",
      method: "POST",
      pattern: "/api/scm/mrp/runs",
      summary: "Trigger an MRP run",
      roles: ["planner", "tenant-admin"],
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 300_000,
      tags: ["mrp"],
    }),
    actionRoute({
      service: "manufacturing-mes",
      id: "manufacturing-mes.work-orders.plan",
      method: "POST",
      pattern: "/api/mes/work-orders/:workOrderId/plan",
      summary: "Plan a manufacturing work order",
      roles: ["production-supervisor", "tenant-admin"],
      tags: ["work-orders"],
    }),
    actionRoute({
      service: "manufacturing-mes",
      id: "manufacturing-mes.work-orders.release",
      method: "POST",
      pattern: "/api/mes/work-orders/:workOrderId/release",
      summary: "Release a manufacturing work order",
      roles: ["production-supervisor", "tenant-admin"],
      tags: ["work-orders"],
    }),
    actionRoute({
      service: "manufacturing-mes",
      id: "manufacturing-mes.work-orders.start",
      method: "POST",
      pattern: "/api/mes/work-orders/:workOrderId/start",
      summary: "Start a manufacturing work order",
      roles: ["production-supervisor", "tenant-admin"],
      tags: ["work-orders"],
    }),
    actionRoute({
      service: "manufacturing-mes",
      id: "manufacturing-mes.work-orders.report",
      method: "POST",
      pattern: "/api/mes/work-orders/:workOrderId/report",
      summary: "Report manufacturing output",
      roles: ["production-supervisor", "tenant-admin"],
      tags: ["work-orders"],
    }),
    actionRoute({
      service: "manufacturing-mes",
      id: "manufacturing-mes.work-orders.complete",
      method: "POST",
      pattern: "/api/mes/work-orders/:workOrderId/complete",
      summary: "Complete a manufacturing work order",
      roles: ["production-supervisor", "tenant-admin"],
      tags: ["work-orders"],
    }),
    actionRoute({
      service: "manufacturing-mes",
      id: "manufacturing-mes.materials.issue",
      method: "POST",
      pattern: "/api/mes/work-orders/:workOrderId/material-issues",
      summary: "Issue material to a work order",
      roles: ["production-supervisor", "tenant-admin"],
      tags: ["materials"],
    }),
    actionRoute({
      service: "manufacturing-mes",
      id: "manufacturing-mes.receipts.create",
      method: "POST",
      pattern: "/api/mes/work-orders/:workOrderId/receipts",
      summary: "Receive output from a work order",
      roles: ["production-supervisor", "tenant-admin"],
      tags: ["receipts"],
    }),
    actionRoute({
      service: "manufacturing-mes",
      id: "manufacturing-mes.receipts.list",
      method: "GET",
      pattern: "/api/mes/work-orders/:workOrderId/receipts",
      summary: "List work-order receipts",
      rateLimit: READ_LIMIT,
      tags: ["receipts"],
    }),
    actionRoute({
      service: "logistics-tms",
      id: "logistics-tms.shipments.track",
      method: "GET",
      pattern: "/api/logistics/shipments/:shipmentId/tracking",
      summary: "Carrier tracking events for a shipment",
      rateLimit: READ_LIMIT,
      tags: ["shipments"],
    }),
  );

  // ---- SRM / PRM / platform ---------------------------------------------
  routes.push(
    ...resourceRoutes({ service: "srm-core", prefix: SRM, resource: "suppliers", writeRoles: ["procurement-manager", "tenant-admin"], operations: ["list", "get", "create", "update"] }),
    ...resourceRoutes({ service: "srm-core", prefix: SRM, resource: "onboarding", writeRoles: ["procurement-manager", "tenant-admin"], operations: ["list", "get", "create"] }),
    ...resourceRoutes({ service: "srm-core", prefix: SRM, resource: "qualifications", writeRoles: ["procurement-manager", "tenant-admin"], operations: ["list", "get", "create"] }),
    ...resourceRoutes({ service: "srm-core", prefix: SRM, resource: "contracts", writeRoles: ["procurement-manager", "tenant-admin"], operations: ["list", "get", "create"] }),
    actionRoute({
      service: "srm-core",
      id: "srm-core.suppliers.activate",
      method: "POST",
      pattern: `${SRM}/suppliers/:supplierId/activate`,
      summary: "Activate a qualified supplier",
      roles: ["procurement-manager", "tenant-admin"],
      tags: ["suppliers"],
    }),
    actionRoute({
      service: "srm-core",
      id: "srm-core.suppliers.suspend",
      method: "POST",
      pattern: `${SRM}/suppliers/:supplierId/suspend`,
      summary: "Suspend a supplier",
      roles: ["procurement-manager", "tenant-admin"],
      tags: ["suppliers"],
    }),
    actionRoute({
      service: "srm-core",
      id: "srm-core.onboarding.submit",
      method: "POST",
      pattern: `${SRM}/onboarding/:onboardingId/submit`,
      summary: "Submit supplier onboarding for review",
      roles: ["procurement-manager", "tenant-admin"],
      tags: ["onboarding"],
    }),
    actionRoute({
      service: "srm-core",
      id: "srm-core.qualifications.start",
      method: "POST",
      pattern: `${SRM}/qualifications/:qualificationId/start`,
      summary: "Start a supplier qualification",
      roles: ["procurement-manager", "tenant-admin"],
      tags: ["qualifications"],
    }),
    actionRoute({
      service: "srm-core",
      id: "srm-core.qualifications.complete",
      method: "POST",
      pattern: `${SRM}/qualifications/:qualificationId/complete`,
      summary: "Complete a supplier qualification",
      roles: ["procurement-manager", "tenant-admin"],
      tags: ["qualifications"],
    }),
    actionRoute({
      service: "srm-core",
      id: "srm-core.contracts.activate",
      method: "POST",
      pattern: `${SRM}/contracts/:contractId/activate`,
      summary: "Activate a signed supplier contract",
      roles: ["procurement-manager", "tenant-admin"],
      tags: ["contracts"],
    }),

    ...resourceRoutes({ service: "procurement-srm", prefix: PROCUREMENT, resource: "requisitions", writeRoles: ["buyer", "procurement-manager", "tenant-admin"], operations: ["list", "get", "create"] }),
    ...resourceRoutes({ service: "procurement-srm", prefix: PROCUREMENT, resource: "purchase-orders", writeRoles: ["procurement-manager", "tenant-admin"], operations: ["list", "get", "create"] }),
    ...resourceRoutes({ service: "procurement-srm", prefix: PROCUREMENT, resource: "approval-requests", readRoles: ["buyer", "procurement-manager", "tenant-admin", "auditor"], operations: ["list", "get"] }),
    ...resourceRoutes({ service: "procurement-srm", prefix: PROCUREMENT, resource: "receipts", writeRoles: ["buyer", "procurement-manager", "tenant-admin"], operations: ["list", "get", "create"] }),
    ...resourceRoutes({ service: "procurement-srm", prefix: PROCUREMENT, resource: "invoices", writeRoles: ["buyer", "procurement-manager", "tenant-admin"], operations: ["list", "get", "create"] }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.requisitions.lines.add",
      method: "POST",
      pattern: `${PROCUREMENT}/requisitions/:requisitionId/lines`,
      summary: "Add a requisition line",
      roles: ["buyer", "procurement-manager", "tenant-admin"],
      tags: ["requisitions"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.requisitions.lines.update",
      method: "PATCH",
      pattern: `${PROCUREMENT}/requisitions/:requisitionId/lines/:lineId`,
      summary: "Update a requisition line",
      roles: ["buyer", "procurement-manager", "tenant-admin"],
      tags: ["requisitions"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.requisitions.submit",
      method: "POST",
      pattern: `${PROCUREMENT}/requisitions/:requisitionId/submit`,
      summary: "Submit a requisition for approval",
      roles: ["buyer", "procurement-manager", "tenant-admin"],
      tags: ["requisitions", "approvals"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.requisitions.withdraw",
      method: "POST",
      pattern: `${PROCUREMENT}/requisitions/:requisitionId/withdraw`,
      summary: "Withdraw a submitted requisition",
      roles: ["buyer", "procurement-manager", "tenant-admin"],
      tags: ["requisitions"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.approvals.inbox",
      method: "GET",
      pattern: `${PROCUREMENT}/approval-requests/inbox`,
      summary: "List approval requests the caller can decide",
      roles: ["buyer", "procurement-manager", "tenant-admin"],
      rateLimit: READ_LIMIT,
      tags: ["approvals"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.approvals.approve",
      method: "POST",
      pattern: `${PROCUREMENT}/approval-requests/:requestId/approve`,
      summary: "Approve a procurement request",
      roles: ["procurement-manager", "tenant-admin"],
      tags: ["approvals"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.approvals.reject",
      method: "POST",
      pattern: `${PROCUREMENT}/approval-requests/:requestId/reject`,
      summary: "Reject a procurement request",
      roles: ["procurement-manager", "tenant-admin"],
      tags: ["approvals"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.purchase-orders.submit",
      method: "POST",
      pattern: `${PROCUREMENT}/purchase-orders/:purchaseOrderId/submit`,
      summary: "Submit a purchase order for approval",
      roles: ["buyer", "procurement-manager", "tenant-admin"],
      tags: ["purchase-orders", "approvals"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.purchase-orders.issue",
      method: "POST",
      pattern: `${PROCUREMENT}/purchase-orders/:purchaseOrderId/issue`,
      summary: "Issue an approved purchase order",
      roles: ["procurement-manager", "tenant-admin"],
      tags: ["purchase-orders"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.receipts.lines.add",
      method: "POST",
      pattern: `${PROCUREMENT}/receipts/:receiptId/lines`,
      summary: "Add a goods-receipt line",
      roles: ["buyer", "procurement-manager", "tenant-admin"],
      tags: ["receipts"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.receipts.post",
      method: "POST",
      pattern: `${PROCUREMENT}/receipts/:receiptId/post`,
      summary: "Post a goods receipt",
      roles: ["buyer", "procurement-manager", "tenant-admin"],
      tags: ["receipts"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.receipts.reverse",
      method: "POST",
      pattern: `${PROCUREMENT}/receipts/:receiptId/reverse`,
      summary: "Reverse a posted goods receipt",
      roles: ["procurement-manager", "tenant-admin"],
      tags: ["receipts"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.invoices.register-and-match",
      method: "POST",
      pattern: `${PROCUREMENT}/invoices/register-and-match`,
      summary: "Register and three-way match a supplier invoice",
      roles: ["buyer", "procurement-manager", "tenant-admin"],
      tags: ["invoices"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.invoices.match",
      method: "POST",
      pattern: `${PROCUREMENT}/invoices/:invoiceId/match`,
      summary: "Run the three-way match for a supplier invoice",
      roles: ["buyer", "procurement-manager", "tenant-admin"],
      tags: ["invoices"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.invoices.resolve-exception",
      method: "POST",
      pattern: `${PROCUREMENT}/invoices/:invoiceId/exceptions/resolve`,
      summary: "Resolve a supplier-invoice match exception",
      roles: ["procurement-manager", "tenant-admin"],
      tags: ["invoices"],
    }),
    actionRoute({
      service: "procurement-srm",
      id: "procurement-srm.invoices.approve-for-payment",
      method: "POST",
      pattern: `${PROCUREMENT}/invoices/:invoiceId/approve-for-payment`,
      summary: "Approve a matched supplier invoice for payment",
      roles: ["procurement-manager", "tenant-admin"],
      tags: ["invoices", "approvals"],
    }),

    ...resourceRoutes({ service: "prm-core", prefix: PRM, resource: "partners", writeRoles: ["partner-manager", "tenant-admin"], operations: ["list", "get", "create", "update"] }),
    ...resourceRoutes({ service: "prm-core", prefix: PRM, resource: "contracts", writeRoles: ["partner-manager", "tenant-admin"], operations: ["list", "get", "create", "update"] }),
    ...resourceRoutes({ service: "prm-core", prefix: PRM, resource: "mdf/requests", writeRoles: ["partner-manager", "tenant-admin"], operations: ["list", "get", "create", "update"], tags: ["mdf"] }),
    ...resourceRoutes({ service: "prm-core", prefix: PRM, resource: "mdf/claims", writeRoles: ["partner-manager", "tenant-admin"], operations: ["list", "get", "create"], tags: ["mdf"] }),
    actionRoute({
      service: "prm-core",
      id: "prm-core.partners.application",
      method: "POST",
      pattern: `${PRM}/partners/:partnerId/application`,
      summary: "Submit a partner application",
      roles: ["partner-manager", "tenant-admin"],
      tags: ["partners"],
    }),
    actionRoute({
      service: "prm-core",
      id: "prm-core.partners.approve",
      method: "POST",
      pattern: `${PRM}/partners/:partnerId/approve`,
      summary: "Approve a partner application",
      roles: ["partner-manager", "tenant-admin"],
      tags: ["partners"],
    }),
    actionRoute({
      service: "prm-core",
      id: "prm-core.partners.activate",
      method: "POST",
      pattern: `${PRM}/partners/:partnerId/activate`,
      summary: "Activate an approved partner",
      roles: ["partner-manager", "tenant-admin"],
      tags: ["partners"],
    }),
    actionRoute({
      service: "prm-core",
      id: "prm-core.partners.suspend",
      method: "POST",
      pattern: `${PRM}/partners/:partnerId/suspend`,
      summary: "Suspend a partner",
      roles: ["partner-manager", "tenant-admin"],
      tags: ["partners"],
    }),
    actionRoute({
      service: "prm-core",
      id: "prm-core.mdf-requests.submit",
      method: "POST",
      pattern: `${PRM}/mdf/requests/:requestId/submit`,
      summary: "Submit an MDF request",
      roles: ["partner-manager", "tenant-admin"],
      tags: ["mdf"],
    }),
    actionRoute({
      service: "prm-core",
      id: "prm-core.mdf-requests.approve",
      method: "POST",
      pattern: `${PRM}/mdf/requests/:requestId/approve`,
      summary: "Approve an MDF request",
      roles: ["partner-manager", "tenant-admin"],
      tags: ["mdf"],
    }),
    ...resourceRoutes({ service: "channel-prm", prefix: "/api/channel", resource: "deal-registrations", writeRoles: ["partner-manager", "sales-manager", "tenant-admin"], operations: ["list", "get", "create", "update"] }),
    ...resourceRoutes({ service: "master-data", prefix: "/api/mdm", resource: "customers", writeRoles: ["data-steward", "tenant-admin"] }),
    ...resourceRoutes({ service: "master-data", prefix: "/api/mdm", resource: "currencies", writeRoles: ["data-steward"], operations: ["list", "get", "update"] }),
    ...resourceRoutes({ service: "identity-access", prefix: IAM, resource: "users", idParam: "userId", readRoles: ["tenant-admin", "auditor"], writeRoles: ["tenant-admin"], operations: ["list", "get", "create", "update"] }),
    ...resourceRoutes({ service: "identity-access", prefix: IAM, resource: "roles", idParam: "code", readRoles: ["tenant-admin", "auditor"], writeRoles: ["tenant-admin"], operations: ["list", "get", "create", "update"] }),
    actionRoute({
      service: "identity-access",
      id: "identity-access.health",
      method: "GET",
      pattern: `${IAM}/health`,
      rewrite: "/health",
      summary: "Identity service liveness",
      auth: { mode: "anonymous" },
      rateLimit: { limit: 600, windowMs: 60_000, key: "global" },
      tags: ["health"],
    }),
    actionRoute({
      service: "identity-access",
      id: "identity-access.me",
      method: "GET",
      pattern: `${IAM}/me`,
      summary: "Read the authenticated identity and permissions",
      rateLimit: READ_LIMIT,
      tags: ["auth"],
    }),
    ...resourceRoutes({ service: "integration-hub", prefix: INTEGRATION, resource: "webhooks", readRoles: ["tenant-admin", "integration-engineer"], writeRoles: ["tenant-admin", "integration-engineer"] }),
    actionRoute({
      service: "integration-hub",
      id: "integration-hub.webhooks.pause",
      method: "POST",
      pattern: `${INTEGRATION}/webhooks/:webhookId/pause`,
      summary: "Pause an integration webhook",
      roles: ["tenant-admin", "integration-engineer"],
      tags: ["webhooks"],
    }),
    actionRoute({
      service: "integration-hub",
      id: "integration-hub.webhooks.resume",
      method: "POST",
      pattern: `${INTEGRATION}/webhooks/:webhookId/resume`,
      summary: "Resume an integration webhook",
      roles: ["tenant-admin", "integration-engineer"],
      tags: ["webhooks"],
    }),
    actionRoute({
      service: "reporting-bi",
      id: "reporting-bi.health",
      method: "GET",
      pattern: `${REPORTING}/health`,
      rewrite: "/health",
      summary: "Reporting service liveness",
      auth: { mode: "anonymous" },
      rateLimit: { limit: 600, windowMs: 60_000, key: "global" },
      tags: ["health"],
    }),
    actionRoute({
      service: "reporting-bi",
      id: "reporting-bi.query",
      method: "POST",
      pattern: `${REPORTING}/query`,
      summary: "Run an analytical cube query",
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 60_000,
      tags: ["reports"],
    }),
    actionRoute({
      service: "reporting-bi",
      id: "reporting-bi.query.scalar",
      method: "POST",
      pattern: `${REPORTING}/query/scalar`,
      summary: "Query one reporting metric",
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 60_000,
      tags: ["reports"],
    }),
    ...resourceRoutes({ service: "reporting-bi", prefix: REPORTING, resource: "exports", readRoles: ["analyst", "tenant-admin"], writeRoles: ["analyst", "tenant-admin"], operations: ["list", "get"] }),
    actionRoute({
      service: "reporting-bi",
      id: "reporting-bi.exports.create",
      method: "POST",
      pattern: `${REPORTING}/exports`,
      summary: "Schedule a data export",
      roles: ["analyst", "tenant-admin"],
      rateLimit: HEAVY_LIMIT,
      tags: ["reports"],
    }),
  );

  // ---- Admin console (tenant operations) ---------------------------------
  routes.push(
    ...resourceRoutes({ service: "admin-console", prefix: ADMIN, resource: "tenants", idParam: "tenantKey", readRoles: ["platform-admin", "tenant-admin", "auditor"], writeRoles: ["platform-admin"], readPermission: "tenant:read", writePermission: "tenant:write", operations: ["list", "get", "create", "update"] }),
    ...resourceRoutes({ service: "admin-console", prefix: ADMIN, resource: "users", idParam: "userKey", readRoles: ["platform-admin", "tenant-admin", "auditor"], writeRoles: ["platform-admin", "tenant-admin"], readPermission: "user:read", writePermission: "user:write" }),
    ...resourceRoutes({ service: "admin-console", prefix: ADMIN, resource: "roles", idParam: "roleCode", readRoles: ["platform-admin", "tenant-admin", "auditor"], writeRoles: ["platform-admin", "tenant-admin"], readPermission: "role:read", writePermission: "role:write" }),
    ...resourceRoutes({ service: "admin-console", prefix: ADMIN, resource: "reference-data", idParam: "setCode", readRoles: ["platform-admin", "tenant-admin", "tenant-operator", "service"], writeRoles: ["platform-admin", "tenant-admin", "tenant-operator"], readPermission: "reference-data:read", writePermission: "reference-data:write" }),
    ...resourceRoutes({ service: "admin-console", prefix: ADMIN, resource: "webhooks", idParam: "webhookId", readRoles: ["platform-admin", "tenant-admin"], writeRoles: ["platform-admin", "tenant-admin"], readPermission: "webhook:read", writePermission: "webhook:write" }),
    ...resourceRoutes({ service: "admin-console", prefix: ADMIN, resource: "feature-flags", idParam: "flagKey", readRoles: ["platform-admin", "tenant-admin", "tenant-operator", "service"], writeRoles: ["platform-admin", "tenant-admin"], readPermission: "feature-flag:read", writePermission: "feature-flag:write" }),
    actionRoute({
      service: "admin-console",
      id: "admin-console.tenants.activate",
      method: "POST",
      pattern: `${ADMIN}/tenants/:tenantKey/activate`,
      summary: "Activate a tenant",
      roles: ["platform-admin"],
      permission: "tenant:write",
      tags: ["tenants"],
    }),
    actionRoute({
      service: "admin-console",
      id: "admin-console.tenants.suspend",
      method: "POST",
      pattern: `${ADMIN}/tenants/:tenantKey/suspend`,
      summary: "Suspend a tenant",
      roles: ["platform-admin"],
      permission: "tenant:write",
      tags: ["tenants"],
    }),
    actionRoute({
      service: "admin-console",
      id: "admin-console.tenants.archive",
      method: "POST",
      pattern: `${ADMIN}/tenants/:tenantKey/archive`,
      summary: "Archive a tenant",
      roles: ["platform-admin"],
      permission: "tenant:write",
      tags: ["tenants"],
    }),
    actionRoute({
      service: "admin-console",
      id: "admin-console.feature-flags.evaluate",
      method: "POST",
      pattern: `${ADMIN}/feature-flags/evaluate`,
      summary: "Evaluate flags for a principal",
      permission: "feature-flag:read",
      rateLimit: { limit: 1_200, windowMs: 60_000, key: "tenant" },
      tags: ["feature-flags"],
    }),
    actionRoute({
      service: "admin-console",
      id: "admin-console.webhooks.test",
      method: "POST",
      pattern: `${ADMIN}/webhooks/:webhookId/test`,
      summary: "Send a test delivery",
      roles: ["platform-admin", "tenant-admin"],
      rateLimit: HEAVY_LIMIT,
      tags: ["webhooks"],
    }),
    actionRoute({
      service: "admin-console",
      id: "admin-console.audit.list",
      method: "GET",
      pattern: `${ADMIN}/audit-log`,
      summary: "Read the tenant audit log",
      roles: ["platform-admin", "tenant-admin", "auditor"],
      permission: "audit:read",
      rateLimit: READ_LIMIT,
      tags: ["audit"],
    }),
  );

  return routes;
}

export function buildRouteTable(catalog?: ServiceCatalog): RouteTable {
  const table = new RouteTable(buildRouteDefinitions());
  if (catalog) {
    const findings = table.audit(catalog.ids());
    const unknown = findings.filter((f) => f.includes("unknown upstream"));
    if (unknown.length > 0) {
      throw new Error(`Route table references unknown services:\n  ${unknown.join("\n  ")}`);
    }
  }
  return table;
}

function singular(resource: string): string {
  if (resource.endsWith("ies")) return `${resource.slice(0, -3)}y`;
  if (resource.endsWith("s")) return resource.slice(0, -1);
  return resource;
}
