import { RouteTable } from "../domain/route-table.js";
import type { HttpMethod, RateLimitPolicy, RouteAuth, RouteDefinition } from "../domain/route.js";
import type { ServiceCatalog } from "../domain/service-catalog.js";

/**
 * The reference route table.
 *
 * Rather than hand-writing five near-identical entries per resource, the
 * standard read/write surface is generated by {@link resourceRoutes} and the
 * genuinely interesting operations (state transitions, reports, bulk jobs) are
 * declared explicitly. Every entry still carries its own auth mode, rate
 * limit and tags, so nothing is lost to the shorthand.
 */

const READ_LIMIT: RateLimitPolicy = { limit: 600, windowMs: 60_000, key: "tenant" };
const WRITE_LIMIT: RateLimitPolicy = { limit: 120, windowMs: 60_000, key: "tenant-user" };
const HEAVY_LIMIT: RateLimitPolicy = { limit: 20, windowMs: 60_000, key: "tenant" };

export interface ResourceRoutesInput {
  readonly service: string;
  readonly prefix: string;
  /** Collection path relative to the prefix, e.g. `products`. */
  readonly resource: string;
  readonly idParam?: string;
  readonly readRoles?: readonly string[];
  readonly writeRoles?: readonly string[];
  readonly readPermission?: string;
  readonly writePermission?: string;
  readonly operations?: readonly ("list" | "get" | "create" | "update" | "delete")[];
  readonly tags?: readonly string[];
}

function auth(roles: readonly string[] | undefined, permission?: string): RouteAuth {
  if (!roles || roles.length === 0) {
    return permission ? { mode: "tenant", allOfPermissions: [permission] } : { mode: "tenant" };
  }
  return {
    mode: "roles",
    anyOfRoles: roles,
    allOfPermissions: permission ? [permission] : undefined,
  };
}

export function resourceRoutes(input: ResourceRoutesInput): RouteDefinition[] {
  const idParam = input.idParam ?? "id";
  const base = `${input.prefix}/${input.resource}`;
  const item = `${base}/:${idParam}`;
  const tags = input.tags ?? [input.resource];
  const operations = input.operations ?? ["list", "get", "create", "update", "delete"];
  const readAuth = auth(input.readRoles, input.readPermission);
  const writeAuth = auth(input.writeRoles, input.writePermission);

  const all: Record<string, RouteDefinition> = {
    list: {
      id: `${input.service}.${input.resource}.list`,
      method: "GET",
      pattern: base,
      upstream: input.service,
      auth: readAuth,
      rateLimit: READ_LIMIT,
      summary: `List ${input.resource}`,
      tags,
      idempotent: true,
    },
    get: {
      id: `${input.service}.${input.resource}.get`,
      method: "GET",
      pattern: item,
      upstream: input.service,
      auth: readAuth,
      rateLimit: READ_LIMIT,
      summary: `Fetch one ${singular(input.resource)}`,
      tags,
      idempotent: true,
    },
    create: {
      id: `${input.service}.${input.resource}.create`,
      method: "POST",
      pattern: base,
      upstream: input.service,
      auth: writeAuth,
      rateLimit: WRITE_LIMIT,
      summary: `Create a ${singular(input.resource)}`,
      tags,
    },
    update: {
      id: `${input.service}.${input.resource}.update`,
      method: "PATCH",
      pattern: item,
      upstream: input.service,
      auth: writeAuth,
      rateLimit: WRITE_LIMIT,
      summary: `Update a ${singular(input.resource)}`,
      tags,
    },
    delete: {
      id: `${input.service}.${input.resource}.delete`,
      method: "DELETE",
      pattern: item,
      upstream: input.service,
      auth: writeAuth,
      rateLimit: WRITE_LIMIT,
      summary: `Delete a ${singular(input.resource)}`,
      tags,
    },
  };

  return operations.map((operation) => all[operation]!);
}

export interface ActionRouteInput {
  readonly service: string;
  readonly method: HttpMethod;
  readonly pattern: string;
  readonly id: string;
  readonly summary: string;
  readonly roles?: readonly string[];
  readonly permission?: string;
  readonly rateLimit?: RateLimitPolicy;
  readonly tags?: readonly string[];
  readonly rewrite?: string;
  readonly timeoutMs?: number;
}

export function actionRoute(input: ActionRouteInput): RouteDefinition {
  return {
    id: input.id,
    method: input.method,
    pattern: input.pattern,
    upstream: input.service,
    auth: auth(input.roles, input.permission),
    rateLimit: input.rateLimit ?? WRITE_LIMIT,
    summary: input.summary,
    tags: input.tags,
    rewrite: input.rewrite,
    timeoutMs: input.timeoutMs,
  };
}

const SALES = "/api/sales";
const PLM = "/api/plm";
const INVENTORY = "/api/inventory";
const FINANCE = "/api/finance";
const QUALITY = "/api/quality";
const ADMIN = "/api/admin";

/** Every route the reference gateway serves. */
export function buildRouteDefinitions(): RouteDefinition[] {
  const routes: RouteDefinition[] = [];

  // ---- Sales -------------------------------------------------------------
  routes.push(
    ...resourceRoutes({
      service: "sales-erp",
      prefix: SALES,
      resource: "quotes",
      readRoles: ["sales-rep", "sales-manager", "tenant-admin", "auditor"],
      writeRoles: ["sales-rep", "sales-manager", "tenant-admin"],
    }),
    ...resourceRoutes({
      service: "sales-erp",
      prefix: SALES,
      resource: "orders",
      readRoles: ["sales-rep", "sales-manager", "tenant-admin", "auditor"],
      writeRoles: ["sales-manager", "tenant-admin"],
      operations: ["list", "get", "create", "update"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.quotes.submit",
      method: "POST",
      pattern: `${SALES}/quotes/:quoteId/submit`,
      summary: "Submit a quote for approval",
      roles: ["sales-rep", "sales-manager"],
      tags: ["quotes"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.quotes.convert",
      method: "POST",
      pattern: `${SALES}/quotes/:quoteId/convert`,
      summary: "Convert an accepted quote into an order",
      roles: ["sales-manager", "tenant-admin"],
      tags: ["quotes", "orders"],
    }),
    actionRoute({
      service: "sales-erp",
      id: "sales-erp.orders.cancel",
      method: "POST",
      pattern: `${SALES}/orders/:orderId/cancel`,
      summary: "Cancel an order and release allocations",
      roles: ["sales-manager", "tenant-admin"],
      tags: ["orders"],
    }),
  );

  // ---- Product / PLM -----------------------------------------------------
  routes.push(
    ...resourceRoutes({
      service: "product-plm",
      prefix: PLM,
      resource: "products",
      idParam: "productId",
      writeRoles: ["product-manager", "tenant-admin"],
    }),
    ...resourceRoutes({
      service: "product-plm",
      prefix: PLM,
      resource: "ecos",
      idParam: "ecoId",
      writeRoles: ["product-manager", "tenant-admin"],
      operations: ["list", "get", "create"],
    }),
    actionRoute({
      service: "product-plm",
      id: "product-plm.products.bom",
      method: "GET",
      pattern: `${PLM}/products/:productId/bom`,
      summary: "Read the effective bill of materials",
      rateLimit: READ_LIMIT,
      tags: ["bom"],
    }),
    actionRoute({
      service: "product-plm",
      id: "product-plm.products.explosion",
      method: "GET",
      pattern: `${PLM}/products/:productId/bom/explosion`,
      summary: "Explode a BOM to component level",
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 30_000,
      tags: ["bom"],
    }),
    actionRoute({
      service: "product-plm",
      id: "product-plm.ecos.approve",
      method: "POST",
      pattern: `${PLM}/ecos/:ecoId/approve`,
      summary: "Approve an engineering change order",
      roles: ["product-manager", "tenant-admin"],
      tags: ["eco"],
    }),
  );

  // ---- Inventory ---------------------------------------------------------
  routes.push(
    ...resourceRoutes({
      service: "inventory-wms",
      prefix: INVENTORY,
      resource: "warehouses",
      writeRoles: ["inventory-manager", "tenant-admin"],
      operations: ["list", "get", "create", "update"],
    }),
    actionRoute({
      service: "inventory-wms",
      id: "inventory-wms.stock.query",
      method: "GET",
      pattern: `${INVENTORY}/stock`,
      summary: "Query on-hand and available stock",
      rateLimit: READ_LIMIT,
      tags: ["stock"],
    }),
    actionRoute({
      service: "inventory-wms",
      id: "inventory-wms.movements.post",
      method: "POST",
      pattern: `${INVENTORY}/movements`,
      summary: "Post a stock movement",
      roles: ["warehouse-operator", "inventory-manager", "tenant-admin"],
      tags: ["stock"],
    }),
    actionRoute({
      service: "inventory-wms",
      id: "inventory-wms.counts.reconcile",
      method: "POST",
      pattern: `${INVENTORY}/counts/:countId/reconcile`,
      summary: "Reconcile a cycle count",
      roles: ["inventory-manager", "tenant-admin"],
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 60_000,
      tags: ["stock"],
    }),
  );

  // ---- Finance -----------------------------------------------------------
  routes.push(
    ...resourceRoutes({
      service: "finance-erp",
      prefix: FINANCE,
      resource: "journals",
      readRoles: ["accountant", "controller", "auditor", "tenant-admin"],
      writeRoles: ["accountant", "controller"],
      operations: ["list", "get", "create"],
    }),
    ...resourceRoutes({
      service: "finance-erp",
      prefix: FINANCE,
      resource: "invoices",
      readRoles: ["accountant", "controller", "auditor", "tenant-admin"],
      writeRoles: ["accountant", "controller"],
      operations: ["list", "get", "create", "update"],
    }),
    actionRoute({
      service: "finance-erp",
      id: "finance-erp.periods.close",
      method: "POST",
      pattern: `${FINANCE}/periods/:periodId/close`,
      summary: "Close an accounting period",
      roles: ["controller"],
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 120_000,
      tags: ["gl"],
    }),
    actionRoute({
      service: "finance-erp",
      id: "finance-erp.reports.trial-balance",
      method: "GET",
      pattern: `${FINANCE}/reports/trial-balance`,
      summary: "Trial balance for a period",
      roles: ["accountant", "controller", "auditor"],
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 30_000,
      tags: ["reports"],
    }),
  );

  // ---- Quality -----------------------------------------------------------
  routes.push(
    ...resourceRoutes({
      service: "quality-qms",
      prefix: QUALITY,
      resource: "ncrs",
      writeRoles: ["quality-inspector", "quality-manager", "tenant-admin"],
      operations: ["list", "get", "create", "update"],
    }),
    ...resourceRoutes({
      service: "quality-qms",
      prefix: QUALITY,
      resource: "capas",
      writeRoles: ["quality-manager", "tenant-admin"],
      operations: ["list", "get", "create", "update"],
    }),
    actionRoute({
      service: "quality-qms",
      id: "quality-qms.inspections.record",
      method: "POST",
      pattern: `${QUALITY}/inspections/:inspectionId/results`,
      summary: "Record inspection results",
      roles: ["quality-inspector", "quality-manager"],
      tags: ["inspections"],
    }),
  );

  // ---- Remaining ERP contexts (standard surface) -------------------------
  routes.push(
    ...resourceRoutes({ service: "marketing-erp", prefix: "/api/marketing", resource: "campaigns", writeRoles: ["marketing-manager", "tenant-admin"] }),
    ...resourceRoutes({ service: "marketing-erp", prefix: "/api/marketing", resource: "leads", writeRoles: ["marketing-manager", "sales-rep", "tenant-admin"], operations: ["list", "get", "create", "update"] }),
    ...resourceRoutes({ service: "supply-chain", prefix: "/api/scm", resource: "plans", writeRoles: ["planner", "tenant-admin"], operations: ["list", "get", "create"] }),
    ...resourceRoutes({ service: "manufacturing-mes", prefix: "/api/mes", resource: "work-orders", writeRoles: ["production-supervisor", "tenant-admin"], operations: ["list", "get", "create", "update"] }),
    ...resourceRoutes({ service: "hcm-erp", prefix: "/api/hcm", resource: "employees", readRoles: ["hr-specialist", "hr-manager", "tenant-admin"], writeRoles: ["hr-manager", "tenant-admin"] }),
    ...resourceRoutes({ service: "logistics-tms", prefix: "/api/logistics", resource: "shipments", writeRoles: ["logistics-coordinator", "tenant-admin"], operations: ["list", "get", "create", "update"] }),
    actionRoute({
      service: "supply-chain",
      id: "supply-chain.mrp.run",
      method: "POST",
      pattern: "/api/scm/mrp/runs",
      summary: "Trigger an MRP run",
      roles: ["planner", "tenant-admin"],
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 300_000,
      tags: ["mrp"],
    }),
    actionRoute({
      service: "logistics-tms",
      id: "logistics-tms.shipments.track",
      method: "GET",
      pattern: "/api/logistics/shipments/:shipmentId/tracking",
      summary: "Carrier tracking events for a shipment",
      rateLimit: READ_LIMIT,
      tags: ["shipments"],
    }),
  );

  // ---- SRM / PRM / platform ---------------------------------------------
  routes.push(
    ...resourceRoutes({ service: "srm-core", prefix: "/api/srm", resource: "suppliers", writeRoles: ["procurement-manager", "tenant-admin"] }),
    ...resourceRoutes({ service: "procurement-srm", prefix: "/api/procurement", resource: "requisitions", writeRoles: ["buyer", "procurement-manager", "tenant-admin"], operations: ["list", "get", "create", "update"] }),
    ...resourceRoutes({ service: "procurement-srm", prefix: "/api/procurement", resource: "purchase-orders", writeRoles: ["procurement-manager", "tenant-admin"], operations: ["list", "get", "create"] }),
    ...resourceRoutes({ service: "prm-core", prefix: "/api/prm", resource: "partners", writeRoles: ["partner-manager", "tenant-admin"] }),
    ...resourceRoutes({ service: "channel-prm", prefix: "/api/channel", resource: "deal-registrations", writeRoles: ["partner-manager", "sales-manager", "tenant-admin"], operations: ["list", "get", "create", "update"] }),
    ...resourceRoutes({ service: "master-data", prefix: "/api/mdm", resource: "customers", writeRoles: ["data-steward", "tenant-admin"] }),
    ...resourceRoutes({ service: "master-data", prefix: "/api/mdm", resource: "currencies", writeRoles: ["data-steward"], operations: ["list", "get", "update"] }),
    ...resourceRoutes({ service: "identity-access", prefix: "/api/iam", resource: "principals", readRoles: ["tenant-admin", "auditor"], writeRoles: ["tenant-admin"] }),
    ...resourceRoutes({ service: "integration-hub", prefix: "/api/integration", resource: "subscriptions", readRoles: ["tenant-admin", "integration-engineer"], writeRoles: ["tenant-admin", "integration-engineer"] }),
    actionRoute({
      service: "reporting-bi",
      id: "reporting-bi.cubes.query",
      method: "POST",
      pattern: "/api/reporting/cubes/:cubeId/query",
      summary: "Query a reporting cube",
      rateLimit: HEAVY_LIMIT,
      timeoutMs: 60_000,
      tags: ["reports"],
    }),
    actionRoute({
      service: "reporting-bi",
      id: "reporting-bi.exports.create",
      method: "POST",
      pattern: "/api/reporting/exports",
      summary: "Schedule a data export",
      roles: ["analyst", "tenant-admin"],
      rateLimit: HEAVY_LIMIT,
      tags: ["reports"],
    }),
  );

  // ---- Admin console (tenant operations) ---------------------------------
  routes.push(
    ...resourceRoutes({ service: "admin-console", prefix: ADMIN, resource: "tenants", idParam: "tenantKey", readRoles: ["platform-admin", "tenant-admin", "auditor"], writeRoles: ["platform-admin"], readPermission: "tenant:read", writePermission: "tenant:write" }),
    ...resourceRoutes({ service: "admin-console", prefix: ADMIN, resource: "users", idParam: "userKey", readRoles: ["platform-admin", "tenant-admin", "auditor"], writeRoles: ["platform-admin", "tenant-admin"], readPermission: "user:read", writePermission: "user:write" }),
    ...resourceRoutes({ service: "admin-console", prefix: ADMIN, resource: "roles", idParam: "roleCode", readRoles: ["platform-admin", "tenant-admin", "auditor"], writeRoles: ["platform-admin", "tenant-admin"], readPermission: "role:read", writePermission: "role:write" }),
    ...resourceRoutes({ service: "admin-console", prefix: ADMIN, resource: "reference-data", idParam: "setCode", readRoles: ["platform-admin", "tenant-admin", "tenant-operator", "service"], writeRoles: ["platform-admin", "tenant-admin", "tenant-operator"], readPermission: "reference-data:read", writePermission: "reference-data:write" }),
    ...resourceRoutes({ service: "admin-console", prefix: ADMIN, resource: "webhooks", idParam: "webhookId", readRoles: ["platform-admin", "tenant-admin"], writeRoles: ["platform-admin", "tenant-admin"], readPermission: "webhook:read", writePermission: "webhook:write" }),
    ...resourceRoutes({ service: "admin-console", prefix: ADMIN, resource: "feature-flags", idParam: "flagKey", readRoles: ["platform-admin", "tenant-admin", "tenant-operator", "service"], writeRoles: ["platform-admin", "tenant-admin"], readPermission: "feature-flag:read", writePermission: "feature-flag:write" }),
    actionRoute({
      service: "admin-console",
      id: "admin-console.feature-flags.evaluate",
      method: "POST",
      pattern: `${ADMIN}/feature-flags/evaluate`,
      summary: "Evaluate flags for a principal",
      permission: "feature-flag:read",
      rateLimit: { limit: 1_200, windowMs: 60_000, key: "tenant" },
      tags: ["feature-flags"],
    }),
    actionRoute({
      service: "admin-console",
      id: "admin-console.webhooks.test",
      method: "POST",
      pattern: `${ADMIN}/webhooks/:webhookId/test`,
      summary: "Send a test delivery",
      roles: ["platform-admin", "tenant-admin"],
      rateLimit: HEAVY_LIMIT,
      tags: ["webhooks"],
    }),
    actionRoute({
      service: "admin-console",
      id: "admin-console.audit.list",
      method: "GET",
      pattern: `${ADMIN}/audit-log`,
      summary: "Read the tenant audit log",
      roles: ["platform-admin", "tenant-admin", "auditor"],
      permission: "audit:read",
      rateLimit: READ_LIMIT,
      tags: ["audit"],
    }),
  );

  return routes;
}

export function buildRouteTable(catalog?: ServiceCatalog): RouteTable {
  const table = new RouteTable(buildRouteDefinitions());
  if (catalog) {
    const findings = table.audit(catalog.ids());
    const unknown = findings.filter((f) => f.includes("unknown upstream"));
    if (unknown.length > 0) {
      throw new Error(`Route table references unknown services:\n  ${unknown.join("\n  ")}`);
    }
  }
  return table;
}

function singular(resource: string): string {
  if (resource.endsWith("ies")) return `${resource.slice(0, -3)}y`;
  if (resource.endsWith("s")) return resource.slice(0, -1);
  return resource;
}
