import { brand, type Brand } from "@enterprise-suite/shared-kernel";
import { ValidationError } from "./errors.js";

/**
 * Country reference data (ISO 3166-1) with the per-country rules master data
 * needs: default currency, postal-code shape and regrouping, whether a
 * subdivision is part of a deliverable address, EU/VAT membership, and the
 * layout used to render a postal label.
 *
 * This is reference data, not tenant data: it is identical for every tenant
 * and is treated as read-only by the services. Tenants extend it by creating
 * code lists, never by editing these rows.
 */

export type CountryCode = Brand<string, "CountryCode">;

/**
 * How a compacted postal code is regrouped for display.
 *
 * `groups` sizes the leading chunks (the remainder becomes the last chunk);
 * `tail` instead separates the final N characters, which is what variable
 * length codes such as UK outcodes need. Reformatting only happens when the
 * compacted length is in `lengths`, so partially entered codes are left alone
 * rather than mangled.
 */
export interface PostalLayout {
  readonly groups?: readonly number[];
  readonly tail?: number;
  readonly separator: string;
  readonly lengths: readonly number[];
  /** Prefix re-applied after compaction, e.g. Latvian "LV-1010". */
  readonly prefix?: string;
}

/** Named label layouts; `renderAddress` resolves the placeholders. */
export type AddressLayout =
  | "postal-city" // most of continental Europe: "1010 Wien"
  | "city-region-postal" // US/CA/AU: "Boston MA 02110"
  | "city-then-postal" // UK/IE/IN: city and postcode on their own lines
  | "postal-region-city"; // JP/CN: largest unit first

export interface CountrySubdivision {
  readonly code: string;
  readonly name: string;
  readonly type: "state" | "province" | "territory" | "district" | "region";
}

export interface Country {
  readonly alpha2: CountryCode;
  readonly alpha3: string;
  readonly numeric: string;
  readonly name: string;
  /** ISO 4217 code of the country's primary legal tender. */
  readonly currency: string;
  readonly callingCode: string;
  readonly euMember: boolean;
  /** VAT registration prefix where it differs from alpha2 (Greece uses EL). */
  readonly vatPrefix?: string;
  readonly postalPattern?: RegExp;
  readonly postalExample?: string;
  readonly postalRequired: boolean;
  readonly postalLayout?: PostalLayout;
  /** A subdivision is mandatory for a deliverable address. */
  readonly regionRequired: boolean;
  readonly addressLayout: AddressLayout;
  /** Present only where the closed list is short and stable enough to enforce. */
  readonly subdivisions?: readonly CountrySubdivision[];
}

const US_STATES: readonly CountrySubdivision[] = [
  { code: "AL", name: "Alabama", type: "state" },
  { code: "AK", name: "Alaska", type: "state" },
  { code: "AZ", name: "Arizona", type: "state" },
  { code: "AR", name: "Arkansas", type: "state" },
  { code: "CA", name: "California", type: "state" },
  { code: "CO", name: "Colorado", type: "state" },
  { code: "CT", name: "Connecticut", type: "state" },
  { code: "DE", name: "Delaware", type: "state" },
  { code: "DC", name: "District of Columbia", type: "district" },
  { code: "FL", name: "Florida", type: "state" },
  { code: "GA", name: "Georgia", type: "state" },
  { code: "HI", name: "Hawaii", type: "state" },
  { code: "ID", name: "Idaho", type: "state" },
  { code: "IL", name: "Illinois", type: "state" },
  { code: "IN", name: "Indiana", type: "state" },
  { code: "IA", name: "Iowa", type: "state" },
  { code: "KS", name: "Kansas", type: "state" },
  { code: "KY", name: "Kentucky", type: "state" },
  { code: "LA", name: "Louisiana", type: "state" },
  { code: "ME", name: "Maine", type: "state" },
  { code: "MD", name: "Maryland", type: "state" },
  { code: "MA", name: "Massachusetts", type: "state" },
  { code: "MI", name: "Michigan", type: "state" },
  { code: "MN", name: "Minnesota", type: "state" },
  { code: "MS", name: "Mississippi", type: "state" },
  { code: "MO", name: "Missouri", type: "state" },
  { code: "MT", name: "Montana", type: "state" },
  { code: "NE", name: "Nebraska", type: "state" },
  { code: "NV", name: "Nevada", type: "state" },
  { code: "NH", name: "New Hampshire", type: "state" },
  { code: "NJ", name: "New Jersey", type: "state" },
  { code: "NM", name: "New Mexico", type: "state" },
  { code: "NY", name: "New York", type: "state" },
  { code: "NC", name: "North Carolina", type: "state" },
  { code: "ND", name: "North Dakota", type: "state" },
  { code: "OH", name: "Ohio", type: "state" },
  { code: "OK", name: "Oklahoma", type: "state" },
  { code: "OR", name: "Oregon", type: "state" },
  { code: "PA", name: "Pennsylvania", type: "state" },
  { code: "PR", name: "Puerto Rico", type: "territory" },
  { code: "RI", name: "Rhode Island", type: "state" },
  { code: "SC", name: "South Carolina", type: "state" },
  { code: "SD", name: "South Dakota", type: "state" },
  { code: "TN", name: "Tennessee", type: "state" },
  { code: "TX", name: "Texas", type: "state" },
  { code: "UT", name: "Utah", type: "state" },
  { code: "VT", name: "Vermont", type: "state" },
  { code: "VA", name: "Virginia", type: "state" },
  { code: "WA", name: "Washington", type: "state" },
  { code: "WV", name: "West Virginia", type: "state" },
  { code: "WI", name: "Wisconsin", type: "state" },
  { code: "WY", name: "Wyoming", type: "state" },
];

const CA_PROVINCES: readonly CountrySubdivision[] = [
  { code: "AB", name: "Alberta", type: "province" },
  { code: "BC", name: "British Columbia", type: "province" },
  { code: "MB", name: "Manitoba", type: "province" },
  { code: "NB", name: "New Brunswick", type: "province" },
  { code: "NL", name: "Newfoundland and Labrador", type: "province" },
  { code: "NS", name: "Nova Scotia", type: "province" },
  { code: "NT", name: "Northwest Territories", type: "territory" },
  { code: "NU", name: "Nunavut", type: "territory" },
  { code: "ON", name: "Ontario", type: "province" },
  { code: "PE", name: "Prince Edward Island", type: "province" },
  { code: "QC", name: "Quebec", type: "province" },
  { code: "SK", name: "Saskatchewan", type: "province" },
  { code: "YT", name: "Yukon", type: "territory" },
];

const AU_STATES: readonly CountrySubdivision[] = [
  { code: "ACT", name: "Australian Capital Territory", type: "territory" },
  { code: "NSW", name: "New South Wales", type: "state" },
  { code: "NT", name: "Northern Territory", type: "territory" },
  { code: "QLD", name: "Queensland", type: "state" },
  { code: "SA", name: "South Australia", type: "state" },
  { code: "TAS", name: "Tasmania", type: "state" },
  { code: "VIC", name: "Victoria", type: "state" },
  { code: "WA", name: "Western Australia", type: "state" },
];

const FIVE_DIGIT: PostalLayout = { groups: [5], separator: "-", lengths: [9] };
const THREE_TWO_SPACE: PostalLayout = { groups: [3], separator: " ", lengths: [5] };

function country(input: Omit<Country, "alpha2"> & { alpha2: string }): Country {
  return { ...input, alpha2: brand<string, "CountryCode">(input.alpha2) };
}

/**
 * The supported country table. Rows carry only what master data enforces;
 * a fuller ISO 3166 list can be layered in without changing any consumer,
 * because everything reads through `findCountry`.
 */
export const COUNTRIES: readonly Country[] = [
  country({
    alpha2: "US",
    alpha3: "USA",
    numeric: "840",
    name: "United States",
    currency: "USD",
    callingCode: "+1",
    euMember: false,
    postalPattern: /^\d{5}(-\d{4})?$/,
    postalExample: "02110",
    postalRequired: true,
    postalLayout: FIVE_DIGIT,
    regionRequired: true,
    addressLayout: "city-region-postal",
    subdivisions: US_STATES,
  }),
  country({
    alpha2: "CA",
    alpha3: "CAN",
    numeric: "124",
    name: "Canada",
    currency: "CAD",
    callingCode: "+1",
    euMember: false,
    postalPattern: /^[A-Z]\d[A-Z] ?\d[A-Z]\d$/,
    postalExample: "K1A 0B1",
    postalRequired: true,
    postalLayout: { groups: [3], separator: " ", lengths: [6] },
    regionRequired: true,
    addressLayout: "city-region-postal",
    subdivisions: CA_PROVINCES,
  }),
  country({
    alpha2: "MX",
    alpha3: "MEX",
    numeric: "484",
    name: "Mexico",
    currency: "MXN",
    callingCode: "+52",
    euMember: false,
    postalPattern: /^\d{5}$/,
    postalExample: "06600",
    postalRequired: true,
    regionRequired: true,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "BR",
    alpha3: "BRA",
    numeric: "076",
    name: "Brazil",
    currency: "BRL",
    callingCode: "+55",
    euMember: false,
    postalPattern: /^\d{5}-?\d{3}$/,
    postalExample: "01310-100",
    postalRequired: true,
    postalLayout: { groups: [5], separator: "-", lengths: [8] },
    regionRequired: true,
    addressLayout: "city-region-postal",
  }),
  country({
    alpha2: "AR",
    alpha3: "ARG",
    numeric: "032",
    name: "Argentina",
    currency: "ARS",
    callingCode: "+54",
    euMember: false,
    postalPattern: /^([A-Z]\d{4}[A-Z]{3}|\d{4})$/,
    postalExample: "C1425DKE",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "CL",
    alpha3: "CHL",
    numeric: "152",
    name: "Chile",
    currency: "CLP",
    callingCode: "+56",
    euMember: false,
    postalPattern: /^\d{7}$/,
    postalExample: "8320000",
    postalRequired: false,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "CO",
    alpha3: "COL",
    numeric: "170",
    name: "Colombia",
    currency: "COP",
    callingCode: "+57",
    euMember: false,
    postalPattern: /^\d{6}$/,
    postalExample: "110111",
    postalRequired: false,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "GB",
    alpha3: "GBR",
    numeric: "826",
    name: "United Kingdom",
    currency: "GBP",
    callingCode: "+44",
    euMember: false,
    postalPattern: /^[A-Z]{1,2}\d[A-Z\d]? ?\d[A-Z]{2}$/,
    postalExample: "SW1A 1AA",
    postalRequired: true,
    postalLayout: { tail: 3, separator: " ", lengths: [5, 6, 7] },
    regionRequired: false,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "IE",
    alpha3: "IRL",
    numeric: "372",
    name: "Ireland",
    currency: "EUR",
    callingCode: "+353",
    euMember: true,
    postalPattern: /^[A-Z]\d{2} ?[A-Z0-9]{4}$/,
    postalExample: "D02 AF30",
    postalRequired: false,
    postalLayout: { groups: [3], separator: " ", lengths: [7] },
    regionRequired: false,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "FR",
    alpha3: "FRA",
    numeric: "250",
    name: "France",
    currency: "EUR",
    callingCode: "+33",
    euMember: true,
    postalPattern: /^\d{5}$/,
    postalExample: "75008",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "DE",
    alpha3: "DEU",
    numeric: "276",
    name: "Germany",
    currency: "EUR",
    callingCode: "+49",
    euMember: true,
    postalPattern: /^\d{5}$/,
    postalExample: "10115",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "NL",
    alpha3: "NLD",
    numeric: "528",
    name: "Netherlands",
    currency: "EUR",
    callingCode: "+31",
    euMember: true,
    postalPattern: /^\d{4} ?[A-Z]{2}$/,
    postalExample: "1012 AB",
    postalRequired: true,
    postalLayout: { groups: [4], separator: " ", lengths: [6] },
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "BE",
    alpha3: "BEL",
    numeric: "056",
    name: "Belgium",
    currency: "EUR",
    callingCode: "+32",
    euMember: true,
    postalPattern: /^\d{4}$/,
    postalExample: "1000",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "LU",
    alpha3: "LUX",
    numeric: "442",
    name: "Luxembourg",
    currency: "EUR",
    callingCode: "+352",
    euMember: true,
    postalPattern: /^(L-)?\d{4}$/,
    postalExample: "L-1855",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "ES",
    alpha3: "ESP",
    numeric: "724",
    name: "Spain",
    currency: "EUR",
    callingCode: "+34",
    euMember: true,
    postalPattern: /^\d{5}$/,
    postalExample: "28013",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "PT",
    alpha3: "PRT",
    numeric: "620",
    name: "Portugal",
    currency: "EUR",
    callingCode: "+351",
    euMember: true,
    postalPattern: /^\d{4}-\d{3}$/,
    postalExample: "1000-100",
    postalRequired: true,
    postalLayout: { groups: [4], separator: "-", lengths: [7] },
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "IT",
    alpha3: "ITA",
    numeric: "380",
    name: "Italy",
    currency: "EUR",
    callingCode: "+39",
    euMember: true,
    postalPattern: /^\d{5}$/,
    postalExample: "00184",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "CH",
    alpha3: "CHE",
    numeric: "756",
    name: "Switzerland",
    currency: "CHF",
    callingCode: "+41",
    euMember: false,
    postalPattern: /^\d{4}$/,
    postalExample: "8001",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "AT",
    alpha3: "AUT",
    numeric: "040",
    name: "Austria",
    currency: "EUR",
    callingCode: "+43",
    euMember: true,
    postalPattern: /^\d{4}$/,
    postalExample: "1010",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "DK",
    alpha3: "DNK",
    numeric: "208",
    name: "Denmark",
    currency: "DKK",
    callingCode: "+45",
    euMember: true,
    postalPattern: /^\d{4}$/,
    postalExample: "1050",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "SE",
    alpha3: "SWE",
    numeric: "752",
    name: "Sweden",
    currency: "SEK",
    callingCode: "+46",
    euMember: true,
    postalPattern: /^\d{3} ?\d{2}$/,
    postalExample: "111 52",
    postalRequired: true,
    postalLayout: THREE_TWO_SPACE,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "NO",
    alpha3: "NOR",
    numeric: "578",
    name: "Norway",
    currency: "NOK",
    callingCode: "+47",
    euMember: false,
    postalPattern: /^\d{4}$/,
    postalExample: "0150",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "FI",
    alpha3: "FIN",
    numeric: "246",
    name: "Finland",
    currency: "EUR",
    callingCode: "+358",
    euMember: true,
    postalPattern: /^\d{5}$/,
    postalExample: "00100",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "IS",
    alpha3: "ISL",
    numeric: "352",
    name: "Iceland",
    currency: "ISK",
    callingCode: "+354",
    euMember: false,
    postalPattern: /^\d{3}$/,
    postalExample: "101",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "PL",
    alpha3: "POL",
    numeric: "616",
    name: "Poland",
    currency: "PLN",
    callingCode: "+48",
    euMember: true,
    postalPattern: /^\d{2}-\d{3}$/,
    postalExample: "00-950",
    postalRequired: true,
    postalLayout: { groups: [2], separator: "-", lengths: [5] },
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "CZ",
    alpha3: "CZE",
    numeric: "203",
    name: "Czechia",
    currency: "CZK",
    callingCode: "+420",
    euMember: true,
    postalPattern: /^\d{3} ?\d{2}$/,
    postalExample: "110 00",
    postalRequired: true,
    postalLayout: THREE_TWO_SPACE,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "SK",
    alpha3: "SVK",
    numeric: "703",
    name: "Slovakia",
    currency: "EUR",
    callingCode: "+421",
    euMember: true,
    postalPattern: /^\d{3} ?\d{2}$/,
    postalExample: "811 01",
    postalRequired: true,
    postalLayout: THREE_TWO_SPACE,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "HU",
    alpha3: "HUN",
    numeric: "348",
    name: "Hungary",
    currency: "HUF",
    callingCode: "+36",
    euMember: true,
    postalPattern: /^\d{4}$/,
    postalExample: "1051",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "RO",
    alpha3: "ROU",
    numeric: "642",
    name: "Romania",
    currency: "RON",
    callingCode: "+40",
    euMember: true,
    postalPattern: /^\d{6}$/,
    postalExample: "010101",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "BG",
    alpha3: "BGR",
    numeric: "100",
    name: "Bulgaria",
    currency: "BGN",
    callingCode: "+359",
    euMember: true,
    postalPattern: /^\d{4}$/,
    postalExample: "1000",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "GR",
    alpha3: "GRC",
    numeric: "300",
    name: "Greece",
    currency: "EUR",
    callingCode: "+30",
    euMember: true,
    vatPrefix: "EL",
    postalPattern: /^\d{3} ?\d{2}$/,
    postalExample: "104 31",
    postalRequired: true,
    postalLayout: THREE_TWO_SPACE,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "HR",
    alpha3: "HRV",
    numeric: "191",
    name: "Croatia",
    currency: "EUR",
    callingCode: "+385",
    euMember: true,
    postalPattern: /^\d{5}$/,
    postalExample: "10000",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "SI",
    alpha3: "SVN",
    numeric: "705",
    name: "Slovenia",
    currency: "EUR",
    callingCode: "+386",
    euMember: true,
    postalPattern: /^\d{4}$/,
    postalExample: "1000",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "EE",
    alpha3: "EST",
    numeric: "233",
    name: "Estonia",
    currency: "EUR",
    callingCode: "+372",
    euMember: true,
    postalPattern: /^\d{5}$/,
    postalExample: "10111",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "LV",
    alpha3: "LVA",
    numeric: "428",
    name: "Latvia",
    currency: "EUR",
    callingCode: "+371",
    euMember: true,
    postalPattern: /^(LV-)?\d{4}$/,
    postalExample: "LV-1010",
    postalRequired: true,
    postalLayout: { groups: [], separator: "", lengths: [4], prefix: "LV-" },
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "LT",
    alpha3: "LTU",
    numeric: "440",
    name: "Lithuania",
    currency: "EUR",
    callingCode: "+370",
    euMember: true,
    postalPattern: /^(LT-)?\d{5}$/,
    postalExample: "LT-01100",
    postalRequired: true,
    postalLayout: { groups: [], separator: "", lengths: [5], prefix: "LT-" },
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "TR",
    alpha3: "TUR",
    numeric: "792",
    name: "Türkiye",
    currency: "TRY",
    callingCode: "+90",
    euMember: false,
    postalPattern: /^\d{5}$/,
    postalExample: "34000",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "UA",
    alpha3: "UKR",
    numeric: "804",
    name: "Ukraine",
    currency: "UAH",
    callingCode: "+380",
    euMember: false,
    postalPattern: /^\d{5}$/,
    postalExample: "01001",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "IL",
    alpha3: "ISR",
    numeric: "376",
    name: "Israel",
    currency: "ILS",
    callingCode: "+972",
    euMember: false,
    postalPattern: /^\d{5}(\d{2})?$/,
    postalExample: "6120101",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "AE",
    alpha3: "ARE",
    numeric: "784",
    name: "United Arab Emirates",
    currency: "AED",
    callingCode: "+971",
    euMember: false,
    postalRequired: false,
    regionRequired: false,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "SA",
    alpha3: "SAU",
    numeric: "682",
    name: "Saudi Arabia",
    currency: "SAR",
    callingCode: "+966",
    euMember: false,
    postalPattern: /^\d{5}(-\d{4})?$/,
    postalExample: "11564",
    postalRequired: false,
    regionRequired: false,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "ZA",
    alpha3: "ZAF",
    numeric: "710",
    name: "South Africa",
    currency: "ZAR",
    callingCode: "+27",
    euMember: false,
    postalPattern: /^\d{4}$/,
    postalExample: "8001",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "EG",
    alpha3: "EGY",
    numeric: "818",
    name: "Egypt",
    currency: "EGP",
    callingCode: "+20",
    euMember: false,
    postalPattern: /^\d{5}$/,
    postalExample: "11511",
    postalRequired: false,
    regionRequired: false,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "NG",
    alpha3: "NGA",
    numeric: "566",
    name: "Nigeria",
    currency: "NGN",
    callingCode: "+234",
    euMember: false,
    postalPattern: /^\d{6}$/,
    postalExample: "100001",
    postalRequired: false,
    regionRequired: false,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "KE",
    alpha3: "KEN",
    numeric: "404",
    name: "Kenya",
    currency: "KES",
    callingCode: "+254",
    euMember: false,
    postalPattern: /^\d{5}$/,
    postalExample: "00100",
    postalRequired: false,
    regionRequired: false,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "IN",
    alpha3: "IND",
    numeric: "356",
    name: "India",
    currency: "INR",
    callingCode: "+91",
    euMember: false,
    postalPattern: /^\d{6}$/,
    postalExample: "560001",
    postalRequired: true,
    regionRequired: true,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "CN",
    alpha3: "CHN",
    numeric: "156",
    name: "China",
    currency: "CNY",
    callingCode: "+86",
    euMember: false,
    postalPattern: /^\d{6}$/,
    postalExample: "100000",
    postalRequired: true,
    regionRequired: true,
    addressLayout: "postal-region-city",
  }),
  country({
    alpha2: "JP",
    alpha3: "JPN",
    numeric: "392",
    name: "Japan",
    currency: "JPY",
    callingCode: "+81",
    euMember: false,
    postalPattern: /^\d{3}-?\d{4}$/,
    postalExample: "100-0001",
    postalRequired: true,
    postalLayout: { groups: [3], separator: "-", lengths: [7] },
    regionRequired: true,
    addressLayout: "postal-region-city",
  }),
  country({
    alpha2: "KR",
    alpha3: "KOR",
    numeric: "410",
    name: "South Korea",
    currency: "KRW",
    callingCode: "+82",
    euMember: false,
    postalPattern: /^\d{5}$/,
    postalExample: "04524",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-region-city",
  }),
  country({
    alpha2: "SG",
    alpha3: "SGP",
    numeric: "702",
    name: "Singapore",
    currency: "SGD",
    callingCode: "+65",
    euMember: false,
    postalPattern: /^\d{6}$/,
    postalExample: "018956",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "MY",
    alpha3: "MYS",
    numeric: "458",
    name: "Malaysia",
    currency: "MYR",
    callingCode: "+60",
    euMember: false,
    postalPattern: /^\d{5}$/,
    postalExample: "50450",
    postalRequired: true,
    regionRequired: true,
    addressLayout: "postal-city",
  }),
  country({
    alpha2: "TH",
    alpha3: "THA",
    numeric: "764",
    name: "Thailand",
    currency: "THB",
    callingCode: "+66",
    euMember: false,
    postalPattern: /^\d{5}$/,
    postalExample: "10330",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "VN",
    alpha3: "VNM",
    numeric: "704",
    name: "Vietnam",
    currency: "VND",
    callingCode: "+84",
    euMember: false,
    postalPattern: /^\d{5,6}$/,
    postalExample: "100000",
    postalRequired: false,
    regionRequired: false,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "ID",
    alpha3: "IDN",
    numeric: "360",
    name: "Indonesia",
    currency: "IDR",
    callingCode: "+62",
    euMember: false,
    postalPattern: /^\d{5}$/,
    postalExample: "10110",
    postalRequired: true,
    regionRequired: true,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "PH",
    alpha3: "PHL",
    numeric: "608",
    name: "Philippines",
    currency: "PHP",
    callingCode: "+63",
    euMember: false,
    postalPattern: /^\d{4}$/,
    postalExample: "1226",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "AU",
    alpha3: "AUS",
    numeric: "036",
    name: "Australia",
    currency: "AUD",
    callingCode: "+61",
    euMember: false,
    postalPattern: /^\d{4}$/,
    postalExample: "3000",
    postalRequired: true,
    regionRequired: true,
    addressLayout: "city-region-postal",
    subdivisions: AU_STATES,
  }),
  country({
    alpha2: "NZ",
    alpha3: "NZL",
    numeric: "554",
    name: "New Zealand",
    currency: "NZD",
    callingCode: "+64",
    euMember: false,
    postalPattern: /^\d{4}$/,
    postalExample: "6011",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "HK",
    alpha3: "HKG",
    numeric: "344",
    name: "Hong Kong",
    currency: "HKD",
    callingCode: "+852",
    euMember: false,
    postalRequired: false,
    regionRequired: false,
    addressLayout: "city-then-postal",
  }),
  country({
    alpha2: "TW",
    alpha3: "TWN",
    numeric: "158",
    name: "Taiwan",
    currency: "TWD",
    callingCode: "+886",
    euMember: false,
    postalPattern: /^\d{3}(\d{2})?$/,
    postalExample: "100",
    postalRequired: true,
    regionRequired: false,
    addressLayout: "postal-region-city",
  }),
];

const BY_ALPHA2 = new Map(COUNTRIES.map((c) => [String(c.alpha2), c]));
const BY_ALPHA3 = new Map(COUNTRIES.map((c) => [c.alpha3, c]));
const BY_NUMERIC = new Map(COUNTRIES.map((c) => [c.numeric, c]));

/** Resolves alpha-2, alpha-3 or numeric codes; returns undefined when unknown. */
export function findCountry(code: string): Country | undefined {
  const normalized = code.trim().toUpperCase();
  return (
    BY_ALPHA2.get(normalized) ?? BY_ALPHA3.get(normalized) ?? BY_NUMERIC.get(normalized.padStart(3, "0"))
  );
}

export function requireCountry(code: string): Country {
  const found = findCountry(code);
  if (!found) throw ValidationError.single("countryCode", `unknown country "${code}"`);
  return found;
}

export function countryCode(value: string): CountryCode {
  return requireCountry(value).alpha2;
}

export function isEuMember(code: string): boolean {
  return findCountry(code)?.euMember ?? false;
}

/** VAT prefix for the country, which is the alpha-2 code except for Greece. */
export function vatPrefixFor(code: string): string | undefined {
  const found = findCountry(code);
  if (!found) return undefined;
  return found.vatPrefix ?? String(found.alpha2);
}

/** The country a VAT prefix belongs to ("EL" -> Greece, "DE" -> Germany). */
export function countryForVatPrefix(prefix: string): Country | undefined {
  const normalized = prefix.trim().toUpperCase();
  return COUNTRIES.find(
    (candidate) => (candidate.vatPrefix ?? String(candidate.alpha2)) === normalized,
  );
}

export function subdivisionsOf(code: string): readonly CountrySubdivision[] {
  return findCountry(code)?.subdivisions ?? [];
}

export function findSubdivision(code: string, region: string): CountrySubdivision | undefined {
  const normalized = region.trim().toUpperCase();
  return subdivisionsOf(code).find(
    (s) => s.code === normalized || s.name.toUpperCase() === normalized,
  );
}
