import type { StageDef } from '../../schema';

const tiles = [
  '####################',
  '#..................#',
  '#..TTT........TTT..#',
  '#..TTT...~~...TTT..#',
  '#........~~........#',
  '#.o......~~......X.#',
  '#........~~........#',
  '#..rr....~~....g...#',
  '#..rr..............#',
  '#......######......#',
  '#......#....#......#',
  '#......#....#..X...#',
  '#..................#',
  '####################',
];

const decor = [
  '                    ',
  ' .        .      .  ',
  '  ===        ===    ',
  '  ===   ~~   ===    ',
  '        ~~          ',
  ' o      ~~      +   ',
  '        ~~          ',
  '  **    ~~    `     ',
  '  **                ',
  '      ......        ',
  '      .    .        ',
  '      .    .  +     ',
  '  ,              ,  ',
  '                    ',
];

const stage: StageDef = {
  id: 'ch01-s04-sink-island',
  chapter: 1,
  index: 4,
  name: 'Sink Island',
  theme: 'kitchen',
  kind: 'story',
  seed: 10104,
  width: 20,
  height: 14,
  tileSize: 16,
  tiles,
  decor,
  spawn: { x: 2, y: 2 },
  entities: [
    { type: 'hole', x: 2, y: 5, id: 'sink-hole' },
    { type: 'cheese', x: 9, y: 2, value: 1 },
    { type: 'cheese', x: 16, y: 3, value: 1 },
    { type: 'cheese', x: 10, y: 10, value: 1 },
    { type: 'cheese', x: 16, y: 11, value: 1 },
    { type: 'cat', x: 16, y: 7, breed: 'scottishFold', patrol: 1, facing: Math.PI },
    { type: 'hazard', x: 9, y: 5, kind: 'water' },
    { type: 'powerUp', x: 3, y: 7, kind: 'featherFoot' },
  ],
  lights: [
    { x: 9, y: 4, radius: 3.6, intensity: 0.55, color: '#6aa8c8', on: true, flicker: 0.12 },
    { x: 4, y: 3, radius: 3.2, intensity: 0.6, color: '#fff1c8', on: true },
    { x: 16, y: 3, radius: 3.2, intensity: 0.6, color: '#fff1c8', on: true },
    { x: 2, y: 5, radius: 2.1, intensity: 0.8, color: '#d4f0a0', on: true },
  ],
  patrols: [
    {
      id: 1,
      loop: true,
      pauseSeconds: 1.3,
      points: [
        { x: 16, y: 7 },
        { x: 16, y: 3 },
        { x: 12, y: 8 },
        { x: 16, y: 11 },
      ],
    },
  ],
  dialogue: [
    { at: 'enter', speaker: 'Narrator', line: 'The sink is a silver river that forgot to be outdoors.' },
    { at: 'enter', speaker: 'Squeak', line: 'Water is a wall that hates fur. East cheese is across the island. I will go around.', delay: 0.5 },
    { at: 'enter', speaker: 'Gran', line: 'If you swallow dishwater I will not be impressed.', delay: 1 },
    { at: 'firstCheese', speaker: 'Squeak', line: 'Damp whiskers. Dry cheddar. Acceptable trade.' },
    { at: 'firstSpotted', speaker: 'Pounce', line: 'The Fold on the far counter is furniture until it is not.' },
    { at: 'halfQuota', speaker: 'Radio', line: 'South alcove is quiet. The grate is a mouse door if the cone pins you east.' },
    { at: 'win', speaker: 'Narrator', line: 'The river keeps dripping. The hole keeps secrets.' },
    { at: 'lose', speaker: 'Pounce', line: 'Wet mouse is slow mouse. Slow mouse is dinner.' },
    { at: 'idle', speaker: 'Narrator', line: 'A drop hits the steel and the whole kitchen flinches.', delay: 8 },
  ],
  hints: {
    ambushSpots: [
      { x: 12, y: 5 },
      { x: 16, y: 8 },
    ],
    searchSpots: [
      { x: 9, y: 2 },
      { x: 16, y: 3 },
      { x: 10, y: 10 },
    ],
    aggression: 0.55,
    scentBias: 0.3,
    hearingBias: 0.7,
    campHoleChance: 0.08,
    leashRadius: 8,
  },
  objectives: [
    { kind: 'quota', value: 4, optional: false, label: 'Bank 4 cheese' },
    { kind: 'noCatch', value: 1, optional: true, label: 'Stay dry and uncaught' },
  ],
  quota: 4,
  parTime: 95,
  lives: 3,
  ambient: 0.58,
  difficulty: 1.8,
  music: 'kitchen-night',
  tags: ['kitchen', 'water', 'island', 'solo-cat'],
};

export default stage;
