import type { StageDef } from '../../schema';

const tiles = [
  '#####################',
  '#...................#',
  '#..TTTT.......TTTT..#',
  '#..T..............T.#',
  '#..T...X......X...T.#',
  '#......X......X.....#',
  '#.o.................#',
  '#......X......X.....#',
  '#..T...X......X...T.#',
  '#..T..............T.#',
  '#..TTTT.......TTTT..#',
  '#................g..#',
  '#...............s...#',
  '#####################',
];

const decor = [
  '                     ',
  ' .         .      .  ',
  '  ====       ====    ',
  '  =              =   ',
  '  =   +      +   =   ',
  '      +      +       ',
  ' o                   ',
  '      +      +       ',
  '  =   +      +   =   ',
  '  =              =   ',
  '  ====       ====    ',
  '                `    ',
  '               ~     ',
  '                     ',
];

const stage: StageDef = {
  id: 'ch01-s06-oven-warmth',
  chapter: 1,
  index: 6,
  name: 'Oven Warmth',
  theme: 'kitchen',
  kind: 'story',
  seed: 10106,
  width: 21,
  height: 14,
  tileSize: 16,
  tiles,
  decor,
  spawn: { x: 10, y: 12 },
  entities: [
    { type: 'hole', x: 2, y: 6, id: 'oven-hole' },
    { type: 'cheese', x: 10, y: 3, value: 1 },
    { type: 'cheese', x: 6, y: 6, value: 1 },
    { type: 'cheese', x: 14, y: 6, value: 1 },
    { type: 'cheese', x: 10, y: 10, value: 1 },
    { type: 'cheese', x: 18, y: 2, value: 1 },
    { type: 'cat', x: 10, y: 6, breed: 'tabby', patrol: 1, facing: 0 },
    { type: 'hazard', x: 7, y: 4, kind: 'sparkWire' },
    { type: 'hazard', x: 13, y: 8, kind: 'sparkWire' },
    { type: 'powerUp', x: 18, y: 12, kind: 'scentMask' },
  ],
  lights: [
    { x: 10, y: 6, radius: 5.5, intensity: 0.85, color: '#ffb060', on: true, flicker: 0.22 },
    { x: 2, y: 6, radius: 2.2, intensity: 0.7, color: '#d4f0a0', on: true },
    { x: 18, y: 3, radius: 3.0, intensity: 0.45, color: '#fff1c8', on: true },
  ],
  patrols: [
    {
      id: 1,
      loop: true,
      pauseSeconds: 0.7,
      points: [
        { x: 10, y: 6 },
        { x: 10, y: 3 },
        { x: 16, y: 6 },
        { x: 10, y: 10 },
        { x: 4, y: 6 },
      ],
    },
  ],
  dialogue: [
    { at: 'enter', speaker: 'Narrator', line: 'The oven is a sleeping dragon that pays rent in heat.' },
    { at: 'enter', speaker: 'Squeak', line: 'U-shaped counters. Cat in the middle. Spark wires like bad jewellery.', delay: 0.4 },
    { at: 'firstCheese', speaker: 'Squeak', line: 'Warm cheddar. Dangerous. Perfect.' },
    { at: 'firstSpotted', speaker: 'Pounce', line: 'You came to the hearth. The hearth came to you.' },
    { at: 'halfQuota', speaker: 'Gran', line: 'If you toast yourself I will not knit a tiny cast.' },
    { at: 'win', speaker: 'Radio', line: 'Heat makes scent lazy. You used that. File it.' },
    { at: 'lose', speaker: 'Pounce', line: 'Crispy. I did not even have to cook.' },
    { at: 'idle', speaker: 'Narrator', line: 'The coil ticks like a clock that wants to be a snake.', delay: 8 },
  ],
  hints: {
    ambushSpots: [
      { x: 10, y: 4 },
      { x: 10, y: 8 },
    ],
    searchSpots: [
      { x: 10, y: 3 },
      { x: 6, y: 6 },
      { x: 14, y: 6 },
      { x: 18, y: 2 },
    ],
    aggression: 0.7,
    scentBias: 0.2,
    hearingBias: 0.45,
    campHoleChance: 0.12,
    leashRadius: 7,
  },
  objectives: [
    { kind: 'quota', value: 4, optional: false, label: 'Bank 4 cheese' },
    { kind: 'reachExit', value: 1, optional: false, label: 'Get back to the west hole' },
  ],
  quota: 4,
  parTime: 105,
  lives: 3,
  ambient: 0.7,
  difficulty: 2.2,
  music: 'kitchen-night',
  tags: ['kitchen', 'heat', 'spark', 'cross', 'solo-cat'],
};

export default stage;
