import type { StageDef } from '../../schema';

const tiles = [
  '####################',
  '#....gggg..........#',
  '#....p..p...TTT....#',
  '#....p..p...TTT....#',
  '#.o..p.............#',
  '#....p..p..........#',
  '#....gggg....X.....#',
  '#..................#',
  '#..rr....~~~~......#',
  '#..rr....~~~~......#',
  '#...........v......#',
  '#...............X..#',
  '#..................#',
  '####################',
];

const decor = [
  '                    ',
  '    ````            ',
  '    |  |   ===      ',
  '    |  |   ===      ',
  ' o  |               ',
  '    |  |            ',
  '    ````    +       ',
  '                    ',
  '  **    ~~~~        ',
  '  **    ~~~~        ',
  '           `        ',
  '               +    ',
  '  ,        ,        ',
  '                    ',
];

const stage: StageDef = {
  id: 'ch01-s07-dishwasher-hum',
  chapter: 1,
  index: 7,
  name: 'Dishwasher Hum',
  theme: 'kitchen',
  kind: 'story',
  seed: 10107,
  width: 20,
  height: 14,
  tileSize: 16,
  tiles,
  decor,
  spawn: { x: 2, y: 12 },
  entities: [
    { type: 'hole', x: 2, y: 4, id: 'washer-hole' },
    { type: 'cheese', x: 6, y: 2, value: 1 },
    { type: 'cheese', x: 14, y: 2, value: 1 },
    { type: 'cheese', x: 8, y: 5, value: 1 },
    { type: 'cheese', x: 12, y: 8, value: 1 },
    { type: 'cheese', x: 17, y: 11, value: 1 },
    { type: 'cat', x: 16, y: 6, breed: 'bombay', patrol: 1, facing: Math.PI },
    { type: 'hazard', x: 11, y: 9, kind: 'water' },
    { type: 'hazard', x: 10, y: 10, kind: 'fan' },
    { type: 'powerUp', x: 3, y: 8, kind: 'noiseBomb' },
  ],
  lights: [
    { x: 6, y: 3, radius: 3.4, intensity: 0.4, color: '#a8c0d0', on: true, flicker: 0.18 },
    { x: 14, y: 3, radius: 3.8, intensity: 0.6, color: '#fff1c8', on: true },
    { x: 2, y: 4, radius: 2.2, intensity: 0.75, color: '#d4f0a0', on: true },
  ],
  patrols: [
    {
      id: 1,
      loop: true,
      pauseSeconds: 0.9,
      points: [
        { x: 16, y: 6 },
        { x: 17, y: 11 },
        { x: 12, y: 12 },
        { x: 16, y: 3 },
      ],
    },
  ],
  dialogue: [
    { at: 'enter', speaker: 'Narrator', line: 'The dishwasher recites a single note until the note becomes weather.' },
    { at: 'enter', speaker: 'Squeak', line: 'Grates over the machine. Pipes like jail. Bombay hunts by ear, not by moon.', delay: 0.5 },
    { at: 'firstCheese', speaker: 'Squeak', line: 'Soap ghost on the rind. I will complain later, in the hole.' },
    { at: 'firstSpotted', speaker: 'Pounce', line: 'I do not need the lamp. I have the hum, and you interrupted it.' },
    { at: 'halfQuota', speaker: 'Radio', line: 'Fan by the leak. It throws scent west. Plan around the weather.' },
    { at: 'win', speaker: 'Gran', line: 'You smell like rinse aid. Wipe your feet anyway.' },
    { at: 'lose', speaker: 'Pounce', line: 'The hum continues. You do not.' },
    { at: 'idle', speaker: 'Narrator', line: 'A fork rattles inside the machine like a tiny prisoner.', delay: 9 },
  ],
  hints: {
    ambushSpots: [
      { x: 8, y: 6 },
      { x: 16, y: 8 },
    ],
    searchSpots: [
      { x: 6, y: 2 },
      { x: 14, y: 2 },
      { x: 12, y: 8 },
    ],
    aggression: 0.58,
    scentBias: 0.4,
    hearingBias: 0.9,
    campHoleChance: 0.07,
    leashRadius: 8,
  },
  objectives: [
    { kind: 'quota', value: 4, optional: false, label: 'Bank 4 cheese' },
    { kind: 'noCatch', value: 1, optional: true, label: 'Quieter than the wash' },
  ],
  quota: 4,
  parTime: 100,
  lives: 3,
  ambient: 0.44,
  difficulty: 2.4,
  music: 'kitchen-night',
  tags: ['kitchen', 'grate', 'pipe', 'hearing', 'solo-cat'],
};

export default stage;
