import type { StageDef } from '../../schema';

const tiles = [
  '################',
  '#.#.#.#.#.#.#..#',
  '#.#.#.#.#.#.#..#',
  '#o#.#.#.#.#.#..#',
  '#.#.#.#.#.#.#X.#',
  '#.#.#.#.#.#.#..#',
  '#.#.#.#.#.#.#..#',
  '#.#.#.#.#.#.#..#',
  '#.#.#.#.#.#.#..#',
  '#.#.#.#.#.#.#..#',
  '#.#.#.#.#.#.#..#',
  '#...........g..#',
  '#..rr..........#',
  '################',
];

const decor = [
  '                ',
  ' + + + + + +    ',
  ' + + + + + +    ',
  'o+ + + + + +    ',
  ' + + + + + + +  ',
  ' + + + + + +    ',
  ' + + + + + +    ',
  ' + + + + + +    ',
  ' + + + + + +    ',
  ' + + + + + +    ',
  ' + + + + + +    ',
  '           `    ',
  '  **            ',
  '                ',
];

const stage: StageDef = {
  id: 'ch01-s05-spice-rack',
  chapter: 1,
  index: 5,
  name: 'Spice Rack',
  theme: 'kitchen',
  kind: 'story',
  seed: 10105,
  width: 16,
  height: 14,
  tileSize: 16,
  tiles,
  decor,
  spawn: { x: 1, y: 12 },
  entities: [
    { type: 'hole', x: 1, y: 3, id: 'spice-hole' },
    { type: 'cheese', x: 3, y: 2, value: 1 },
    { type: 'cheese', x: 5, y: 6, value: 1 },
    { type: 'cheese', x: 7, y: 4, value: 1 },
    { type: 'cheese', x: 9, y: 8, value: 1 },
    { type: 'cheese', x: 11, y: 1, value: 1 },
    { type: 'cat', x: 14, y: 6, breed: 'siamese', patrol: 1, facing: -Math.PI / 2 },
    { type: 'powerUp', x: 13, y: 12, kind: 'speed' },
    { type: 'hazard', x: 13, y: 4, kind: 'glueBoard' },
  ],
  lights: [
    { x: 1, y: 3, radius: 2.0, intensity: 0.7, color: '#d4f0a0', on: true },
    { x: 8, y: 1, radius: 3.5, intensity: 0.5, color: '#fff1c8', on: true },
    { x: 14, y: 11, radius: 3.0, intensity: 0.45, color: '#e8d8b0', on: true },
  ],
  patrols: [
    {
      id: 1,
      loop: false,
      pauseSeconds: 0.5,
      points: [
        { x: 14, y: 2 },
        { x: 14, y: 10 },
        { x: 12, y: 11 },
        { x: 14, y: 6 },
      ],
    },
  ],
  dialogue: [
    { at: 'enter', speaker: 'Squeak', line: 'Shelves like prison bars, if prison smelled of paprika.' },
    { at: 'enter', speaker: 'Radio', line: 'Siamese on the service aisle. Hearing range is rude. Sneak between jars.', delay: 0.5 },
    { at: 'firstCheese', speaker: 'Squeak', line: 'Cumin in my nose. Cheese in my teeth. Even trade.' },
    { at: 'firstSpotted', speaker: 'Pounce', line: 'I heard a jar lid. I heard a heartbeat. Same difference.' },
    { at: 'halfQuota', speaker: 'Gran', line: 'Do not knock the saffron. I am not made of saffron.' },
    { at: 'win', speaker: 'Narrator', line: 'The rack keeps its spices. The hole keeps the cheddar.' },
    { at: 'lose', speaker: 'Pounce', line: 'Seasoned. Convenient.' },
    { at: 'idle', speaker: 'Narrator', line: 'Pepper flakes drift like slow sparks.', delay: 7 },
  ],
  hints: {
    ambushSpots: [
      { x: 13, y: 11 },
      { x: 14, y: 3 },
    ],
    searchSpots: [
      { x: 3, y: 2 },
      { x: 7, y: 4 },
      { x: 11, y: 1 },
    ],
    aggression: 0.62,
    scentBias: 0.25,
    hearingBias: 0.85,
    campHoleChance: 0.05,
    leashRadius: 9,
  },
  objectives: [
    { kind: 'quota', value: 4, optional: false, label: 'Bank 4 cheese' },
    { kind: 'noCatch', value: 1, optional: true, label: 'Silent aisle' },
  ],
  quota: 4,
  parTime: 100,
  lives: 3,
  ambient: 0.5,
  difficulty: 2,
  music: 'kitchen-night',
  tags: ['kitchen', 'narrow', 'hearing', 'solo-cat'],
};

export default stage;
