import type { StageDef } from '../../schema';

const tiles = [
  '########################',
  '#......................#',
  '#..rrr....XXXX.........#',
  '#..rrr....X..X....TTT..#',
  '#.........X..X....TTT..#',
  '#.o.......XXXX.........#',
  '#......................#',
  '#......##########......#',
  '#......D........#......#',
  '#......#..g..X..#..X...#',
  '#......#........#......#',
  '#......##########......#',
  '#......................#',
  '#......................#',
  '########################',
];

const decor = [
  '                        ',
  ' .        .        .    ',
  '  ***    ++++           ',
  '  ***    +  +    ===    ',
  '         +  +    ===    ',
  ' o       ++++           ',
  '                        ',
  '      ..........        ',
  '      =        .        ',
  '      .  `  +  .  +     ',
  '      .        .        ',
  '      ..........        ',
  '  ,                  ,  ',
  '                        ',
  '                        ',
];

const stage: StageDef = {
  id: 'ch01-s08-gran-returns',
  chapter: 1,
  index: 8,
  name: 'Gran Returns',
  theme: 'kitchen',
  kind: 'story',
  seed: 10108,
  width: 24,
  height: 15,
  tileSize: 16,
  tiles,
  decor,
  spawn: { x: 2, y: 2 },
  entities: [
    { type: 'hole', x: 2, y: 5, id: 'gran-hole' },
    { type: 'cheese', x: 12, y: 3, value: 1 },
    { type: 'cheese', x: 18, y: 3, value: 1 },
    { type: 'cheese', x: 10, y: 9, value: 1 },
    { type: 'cheese', x: 14, y: 9, value: 1, guarded: true },
    { type: 'cheese', x: 20, y: 9, value: 1 },
    { type: 'cheese', x: 21, y: 13, value: 1 },
    { type: 'key', x: 16, y: 13, keyId: 'gran-pantry' },
    { type: 'door', x: 7, y: 8, id: 'pantry-door', locked: true, keyId: 'gran-pantry' },
    { type: 'cat', x: 20, y: 5, breed: 'persian', patrol: 1, facing: Math.PI },
    { type: 'cat', x: 12, y: 13, breed: 'tabby', patrol: 2, facing: 0 },
    { type: 'powerUp', x: 3, y: 12, kind: 'extraLife' },
    { type: 'hazard', x: 21, y: 9, kind: 'broom' },
  ],
  lights: [
    { x: 4, y: 3, radius: 4.0, intensity: 0.7, color: '#fff1c8', on: true },
    { x: 18, y: 4, radius: 3.5, intensity: 0.55, color: '#ffe8a0', on: true },
    { x: 11, y: 9, radius: 3.0, intensity: 0.5, color: '#e8d8b0', on: true },
    { x: 2, y: 5, radius: 2.3, intensity: 0.8, color: '#d4f0a0', on: true },
  ],
  patrols: [
    {
      id: 1,
      loop: true,
      pauseSeconds: 1.8,
      points: [
        { x: 20, y: 5 },
        { x: 21, y: 2 },
        { x: 18, y: 6 },
        { x: 21, y: 12 },
      ],
    },
    {
      id: 2,
      loop: true,
      pauseSeconds: 0.6,
      points: [
        { x: 12, y: 13 },
        { x: 3, y: 13 },
        { x: 21, y: 13 },
        { x: 12, y: 12 },
      ],
    },
  ],
  dialogue: [
    { at: 'enter', speaker: 'Gran', line: 'I am home early. The pantry is locked because you exist. The key is south. The Persian is a doorstop with opinions.' },
    { at: 'enter', speaker: 'Squeak', line: 'Two cats. Five wedges. A broom that wants to be a rumour. Fine.', delay: 0.8 },
    { at: 'firstCheese', speaker: 'Squeak', line: 'One down. The pantry still pretends to be a vault.' },
    { at: 'firstSpotted', speaker: 'Pounce', line: 'Gran brought backup. Backup brought a broom.' },
    { at: 'halfQuota', speaker: 'Radio', line: 'Key first, pantry second, hole always. The tabby patrols the south like a train.' },
    { at: 'lowLives', speaker: 'Gran', line: 'Thimble is on the west rug. Use it. Do not make me knit another.' },
    { at: 'win', speaker: 'Gran', line: 'You emptied my pantry and lived. Sit. Nibble. Do not gloat with your mouth full.' },
    { at: 'lose', speaker: 'Pounce', line: 'Tell Gran the snack ran out of futures.' },
    { at: 'idle', speaker: 'Narrator', line: 'The broom leans at an angle that means business.', delay: 8 },
  ],
  hints: {
    ambushSpots: [
      { x: 3, y: 5 },
      { x: 8, y: 8 },
      { x: 20, y: 8 },
    ],
    searchSpots: [
      { x: 12, y: 3 },
      { x: 10, y: 9 },
      { x: 16, y: 13 },
      { x: 21, y: 13 },
    ],
    aggression: 0.72,
    scentBias: 0.5,
    hearingBias: 0.55,
    campHoleChance: 0.34,
    leashRadius: 10,
  },
  objectives: [
    { kind: 'quota', value: 5, optional: false, label: 'Bank 5 cheese' },
    { kind: 'reachExit', value: 1, optional: false, label: 'Get back to Gran\'s hole' },
    { kind: 'noCatch', value: 1, optional: true, label: 'Do not become an anecdote' },
  ],
  quota: 5,
  parTime: 130,
  lives: 3,
  ambient: 0.58,
  difficulty: 2.8,
  music: 'kitchen-night',
  tags: ['kitchen', 'boss', 'key', 'multi-cat', 'chapter-end'],
};

export default stage;
