import type { StageDef } from '../../schema';

const tiles = [
  '########################',
  '#pppp..............pppp#',
  '#p..................p..#',
  '#p..ooo.............p..#',
  '#p.................gp..#',
  '#pppp.....~~~~.....pppp#',
  '#.........~~~~.........#',
  '#..X......~~~~......X..#',
  '#......................#',
  '#pppp..............pppp#',
  '#p..................p..#',
  '#p....g.............p..#',
  '#pppp..............pppp#',
  '########################',
];

const decor = [
  '                        ',
  '||||              ||||  ',
  '|                  |    ',
  '|  ooo             |    ',
  '|                 `|    ',
  '||||     ~~~~     ||||  ',
  '         ~~~~           ',
  '  +      ~~~~      +    ',
  '                        ',
  '||||              ||||  ',
  '|                  |    ',
  '|     `            |    ',
  '||||              ||||  ',
  '                        ',
];

const stage: StageDef = {
  id: 'ch04-s01-pipe-crawl',
  chapter: 4,
  index: 1,
  name: 'Pipe Crawl',
  theme: 'sewer',
  kind: 'story',
  seed: 40401,
  width: 24,
  height: 14,
  tileSize: 16,
  tiles,
  decor,
  spawn: { x: 6, y: 2 },
  entities: [
    { type: 'hole', x: 5, y: 3, id: 'pipe-hole' },
    { type: 'cheese', x: 12, y: 2, value: 1 },
    { type: 'cheese', x: 18, y: 4, value: 1 },
    { type: 'cheese', x: 6, y: 8, value: 1 },
    { type: 'cheese', x: 17, y: 8, value: 1 },
    { type: 'cheese', x: 8, y: 11, value: 1 },
    { type: 'cat', x: 12, y: 7, breed: 'sphynx', patrol: 1, facing: 0 },
    { type: 'hazard', x: 12, y: 6, kind: 'water' },
    { type: 'powerUp', x: 21, y: 11, kind: 'featherFoot' },
  ],
  lights: [
    { x: 5, y: 3, radius: 2.4, intensity: 0.65, color: '#c6e36a', on: true },
    { x: 12, y: 6, radius: 3.5, intensity: 0.3, color: '#6d8b3e', on: true, flicker: 0.2 },
    { x: 20, y: 10, radius: 3.0, intensity: 0.4, color: '#9ad14a', on: true },
  ],
  patrols: [
    {
      id: 1,
      loop: true,
      pauseSeconds: 0.8,
      points: [
        { x: 12, y: 7 },
        { x: 20, y: 8 },
        { x: 12, y: 11 },
        { x: 4, y: 8 },
      ],
    },
  ],
  dialogue: [
    { at: 'enter', speaker: 'Narrator', line: 'Every footstep arrives twice. The second one is shopping for you.' },
    { at: 'enter', speaker: 'Radio', line: 'Cats hate grate. You do not. That is the doctrine. Hole is a triple-o nest in the north pipe.', delay: 0.5 },
    { at: 'firstCheese', speaker: 'Squeak', line: 'It tastes like a rumour of a dairy that fell down a drain and refused to die.' },
    { at: 'firstSpotted', speaker: 'Pounce', line: 'The sphynx does not need fur. It has your yesterday.' },
    { at: 'halfQuota', speaker: 'Gran', line: 'If it ripples it is water. If it ripples and purrs, leave the chapter.' },
    { at: 'win', speaker: 'Squeak', line: 'Pipes forgot to ask permission. I did not.' },
    { at: 'lose', speaker: 'Pounce', line: 'Echo collected.' },
    { at: 'idle', speaker: 'Narrator', line: 'A drip keeps time for a band that never arrives.', delay: 8 },
  ],
  hints: {
    ambushSpots: [
      { x: 12, y: 5 },
      { x: 6, y: 3 },
    ],
    searchSpots: [
      { x: 12, y: 2 },
      { x: 18, y: 4 },
      { x: 8, y: 11 },
    ],
    aggression: 0.6,
    scentBias: 0.95,
    hearingBias: 0.5,
    campHoleChance: 0.14,
    leashRadius: 10,
  },
  objectives: [
    { kind: 'quota', value: 4, optional: false, label: 'Bank 4 cheese' },
    { kind: 'noCatch', value: 1, optional: true, label: 'Stay off the scent ledger' },
  ],
  quota: 4,
  parTime: 120,
  lives: 3,
  ambient: 0.3,
  difficulty: 4,
  music: 'sewer-flow',
  tags: ['sewer', 'pipe', 'water', 'sphynx', 'solo-cat'],
};

export default stage;
