import type { StageDef } from '../../schema';

const tiles = [
  '#####################',
  '#...................#',
  '#..#####.....#####..#',
  '#..#rrr#.....#TTT#..#',
  '#..#rrr#.....#TTT#..#',
  '#..##D##.....##D##..#',
  '#...................#',
  '#.o....XXXXX........#',
  '#......X...X....G...#',
  '#......XXXXX........#',
  '#...................#',
  '#..rr...........s...#',
  '#####################',
];

const decor = [
  '                     ',
  '  .        .      .  ',
  '  .....     .....    ',
  '  .***.     .===.    ',
  '  .***.     .===.    ',
  '  ..D..     ..D..    ',
  '                     ',
  ' o    +++++          ',
  '      +   +    =     ',
  '      +++++          ',
  '                     ',
  '  **           ~     ',
  '                     ',
];

const stage: StageDef = {
  id: 'ch06-s01-ticket-booth',
  chapter: 6,
  index: 1,
  name: 'Ticket Booth',
  theme: 'carnival',
  kind: 'story',
  seed: 60601,
  width: 21,
  height: 13,
  tileSize: 16,
  tiles,
  decor,
  spawn: { x: 2, y: 11 },
  entities: [
    { type: 'hole', x: 2, y: 7, id: 'booth-hole' },
    { type: 'cheese', x: 5, y: 3, value: 1 },
    { type: 'cheese', x: 15, y: 3, value: 1 },
    { type: 'cheese', x: 9, y: 8, value: 1 },
    { type: 'cheese', x: 17, y: 8, value: 1 },
    { type: 'cheese', x: 18, y: 11, value: 1 },
    { type: 'key', x: 10, y: 11, keyId: 'booth-key' },
    { type: 'door', x: 5, y: 5, id: 'west-booth', locked: true, keyId: 'booth-key' },
    { type: 'door', x: 15, y: 5, id: 'east-booth', locked: false },
    { type: 'cat', x: 10, y: 6, breed: 'bengal', patrol: 1, facing: Math.PI / 2 },
    { type: 'powerUp', x: 18, y: 1, kind: 'speed' },
    { type: 'hazard', x: 10, y: 10, kind: 'broom' },
  ],
  lights: [
    { x: 5, y: 3, radius: 3.0, intensity: 0.7, color: '#ffd45a', on: true, flicker: 0.25 },
    { x: 15, y: 3, radius: 3.0, intensity: 0.7, color: '#ffd45a', on: true, flicker: 0.2 },
    { x: 2, y: 7, radius: 2.2, intensity: 0.75, color: '#d4f0a0', on: true },
  ],
  patrols: [
    {
      id: 1,
      loop: true,
      pauseSeconds: 0.4,
      points: [
        { x: 10, y: 6 },
        { x: 18, y: 6 },
        { x: 10, y: 1 },
        { x: 3, y: 6 },
      ],
    },
  ],
  dialogue: [
    { at: 'enter', speaker: 'Radio', line: 'Step right up. Prize cheese in the booths. Bengal thinks the midway is a hunting ground.' },
    { at: 'enter', speaker: 'Squeak', line: 'West booth locked. Key on the south rug. East booth is a dare with no lock.', delay: 0.5 },
    { at: 'firstCheese', speaker: 'Squeak', line: 'Carnival cheddar. It sparkles in a way cheese should not.' },
    { at: 'firstSpotted', speaker: 'Pounce', line: 'I won you a stuffed mouse once. It was practice.' },
    { at: 'halfQuota', speaker: 'Gran', line: 'Do not ride the stairs unless the Bengal is looking at a bulb.' },
    { at: 'win', speaker: 'Narrator', line: 'The closed carnival remains honest. You remain fed.' },
    { at: 'lose', speaker: 'Pounce', line: 'Prize claimed.' },
    { at: 'idle', speaker: 'Narrator', line: 'A ticket wheel clicks one seat for nobody.', delay: 8 },
  ],
  hints: {
    ambushSpots: [
      { x: 10, y: 7 },
      { x: 5, y: 6 },
    ],
    searchSpots: [
      { x: 5, y: 3 },
      { x: 15, y: 3 },
      { x: 10, y: 11 },
    ],
    aggression: 0.85,
    scentBias: 0.4,
    hearingBias: 0.55,
    campHoleChance: 0.08,
    leashRadius: 9,
  },
  objectives: [
    { kind: 'quota', value: 4, optional: false, label: 'Bank 4 cheese' },
    { kind: 'noCatch', value: 1, optional: true, label: 'Do not become a prize' },
  ],
  quota: 4,
  parTime: 120,
  lives: 3,
  ambient: 0.48,
  difficulty: 5,
  music: 'carnival-closed',
  tags: ['carnival', 'booth', 'key', 'bengal', 'solo-cat'],
};

export default stage;
