import type { StageDef } from '../../schema';

const tiles = [
  '##########################',
  '#rrrr................rrrr#',
  '#........................#',
  '#....TTT..........TTT....#',
  '#....T..............T....#',
  '#....TTT..........TTT....#',
  '#........................#',
  '#.o.........GG..........s#',
  '#...........GG...........#',
  '#....TTT..........TTT....#',
  '#....T..............T....#',
  '#....TTT..........TTT....#',
  '#........................#',
  '#rrrr................rrrr#',
  '##########################',
];

const decor = [
  '                          ',
  '****                ****  ',
  '                          ',
  '    ===            ===    ',
  '    =                =    ',
  '    ===            ===    ',
  '                          ',
  ' o         ==           ~ ',
  '           ==             ',
  '    ===            ===    ',
  '    =                =    ',
  '    ===            ===    ',
  '                          ',
  '****                ****  ',
  '                          ',
];

const stage: StageDef = {
  id: 'ch07-s01-marble-foyer',
  chapter: 7,
  index: 1,
  name: 'Marble Foyer',
  theme: 'museum',
  kind: 'story',
  seed: 70701,
  width: 26,
  height: 15,
  tileSize: 16,
  tiles,
  decor,
  spawn: { x: 2, y: 2 },
  entities: [
    { type: 'hole', x: 2, y: 7, id: 'foyer-hole' },
    { type: 'cheese', x: 6, y: 4, value: 1, guarded: true },
    { type: 'cheese', x: 19, y: 4, value: 1, guarded: true },
    { type: 'cheese', x: 6, y: 10, value: 1 },
    { type: 'cheese', x: 19, y: 10, value: 1 },
    { type: 'cheese', x: 13, y: 7, value: 1 },
    { type: 'cheese', x: 23, y: 2, value: 1 },
    { type: 'cat', x: 13, y: 2, breed: 'maineCoon', patrol: 1, facing: Math.PI / 2 },
    { type: 'cat', x: 13, y: 12, breed: 'britishShorthair', patrol: 2, facing: -Math.PI / 2 },
    { type: 'powerUp', x: 2, y: 13, kind: 'scentMask' },
    { type: 'hazard', x: 13, y: 13, kind: 'glueBoard' },
  ],
  lights: [
    { x: 6, y: 4, radius: 3.4, intensity: 0.65, color: '#f4e6c4', on: true },
    { x: 19, y: 4, radius: 3.4, intensity: 0.65, color: '#f4e6c4', on: true },
    { x: 13, y: 7, radius: 4.0, intensity: 0.5, color: '#b08a3c', on: true },
    { x: 2, y: 7, radius: 2.2, intensity: 0.8, color: '#d4f0a0', on: true },
  ],
  patrols: [
    {
      id: 1,
      loop: true,
      pauseSeconds: 1.0,
      points: [
        { x: 13, y: 2 },
        { x: 23, y: 2 },
        { x: 3, y: 2 },
        { x: 13, y: 5 },
      ],
    },
    {
      id: 2,
      loop: true,
      pauseSeconds: 1.5,
      points: [
        { x: 13, y: 12 },
        { x: 3, y: 13 },
        { x: 23, y: 13 },
        { x: 13, y: 10 },
      ],
    },
  ],
  dialogue: [
    { at: 'enter', speaker: 'Narrator', line: 'Marble remembers every nail click. The portraits have not blinked in a century.' },
    { at: 'enter', speaker: 'Pounce', line: 'Do not touch the vases. Touching the vases makes the Maine Coon invent new physics.', delay: 0.5 },
    { at: 'firstCheese', speaker: 'Squeak', line: 'Pedestal cheddar. It was labelled "do not nibble". I nibbled.' },
    { at: 'firstSpotted', speaker: 'Pounce', line: 'The night watch never clocks out. Neither does the shorthair on the south rug.' },
    { at: 'halfQuota', speaker: 'Gran', line: 'Rugs are sneak made of wool. Also they are where the campers sit.' },
    { at: 'win', speaker: 'Squeak', line: 'Glass cases still closed. Hole still open. That is the whole review.' },
    { at: 'lose', speaker: 'Pounce', line: 'Exhibit: mouse, briefly.' },
    { at: 'idle', speaker: 'Narrator', line: 'A skylight draws a slow rectangle across the floor like a searchlight that pays taxes.', delay: 10 },
  ],
  hints: {
    ambushSpots: [
      { x: 13, y: 7 },
      { x: 3, y: 7 },
      { x: 22, y: 7 },
    ],
    searchSpots: [
      { x: 6, y: 4 },
      { x: 19, y: 4 },
      { x: 6, y: 10 },
      { x: 19, y: 10 },
    ],
    aggression: 0.6,
    scentBias: 0.35,
    hearingBias: 0.7,
    campHoleChance: 0.25,
    leashRadius: 12,
  },
  objectives: [
    { kind: 'quota', value: 5, optional: false, label: 'Bank 5 cheese' },
    { kind: 'noCatch', value: 1, optional: true, label: 'Leave no fingerprints' },
  ],
  quota: 5,
  parTime: 140,
  lives: 3,
  ambient: 0.55,
  difficulty: 5.5,
  music: 'museum-echo',
  tags: ['museum', 'marble', 'multi-cat', 'open'],
};

export default stage;
