import type { StageDef } from '../../schema';

const tiles = [
  '######################',
  '#vv....########....vv#',
  '#vv....D......D....vv#',
  '#......#..GG..#......#',
  '#.o....#..GG..#....X.#',
  '#......########......#',
  '#....................#',
  '#..#####......#####..#',
  '#..#ggg#......#ggg#..#',
  '#..#g.g#......#g.g#..#',
  '#..#####......#####..#',
  '#....................#',
  '#.................s..#',
  '######################',
];

const decor = [
  '                      ',
  '``    ........    ``  ',
  '``    =      =    ``  ',
  '      .  ==  .        ',
  ' o    .  ==  .    +   ',
  '      ........        ',
  '                      ',
  '  .....      .....    ',
  '  .```.      .```.    ',
  '  .`.` .     .`.` .   ',
  '  .....      .....    ',
  '                      ',
  '                 ~    ',
  '                      ',
];

const stage: StageDef = {
  id: 'ch12-s01-airlock',
  chapter: 12,
  index: 1,
  name: 'Airlock',
  theme: 'moonLab',
  kind: 'story',
  seed: 120201,
  width: 22,
  height: 14,
  tileSize: 16,
  tiles,
  decor,
  spawn: { x: 4, y: 12 },
  entities: [
    { type: 'hole', x: 2, y: 4, id: 'airlock-hole' },
    { type: 'cheese', x: 10, y: 3, value: 1, guarded: true },
    { type: 'cheese', x: 12, y: 3, value: 1, guarded: true },
    { type: 'cheese', x: 6, y: 8, value: 1 },
    { type: 'cheese', x: 16, y: 8, value: 1 },
    { type: 'cheese', x: 19, y: 4, value: 1 },
    { type: 'cheese', x: 19, y: 12, value: 1 },
    { type: 'key', x: 6, y: 9, keyId: 'airlock-key' },
    { type: 'door', x: 7, y: 2, id: 'west-lock', locked: true, keyId: 'airlock-key' },
    { type: 'door', x: 14, y: 2, id: 'east-lock', locked: true, keyId: 'airlock-key' },
    { type: 'cat', x: 11, y: 6, breed: 'savannah', patrol: 1, facing: Math.PI / 2 },
    { type: 'cat', x: 19, y: 11, breed: 'bengal', patrol: 2, facing: Math.PI },
    { type: 'powerUp', x: 2, y: 12, kind: 'freeze' },
    { type: 'hazard', x: 11, y: 11, kind: 'sparkWire' },
    { type: 'hazard', x: 3, y: 8, kind: 'vacuum' },
  ],
  lights: [
    { x: 11, y: 3, radius: 3.5, intensity: 0.9, color: '#e8ffff', on: true },
    { x: 2, y: 4, radius: 2.4, intensity: 0.8, color: '#4ad4ff', on: true },
    { x: 6, y: 8, radius: 2.8, intensity: 0.5, color: '#8aa0b4', on: true },
    { x: 16, y: 8, radius: 2.8, intensity: 0.5, color: '#8aa0b4', on: true },
  ],
  patrols: [
    {
      id: 1,
      loop: true,
      pauseSeconds: 0.5,
      points: [
        { x: 11, y: 6 },
        { x: 4, y: 6 },
        { x: 18, y: 6 },
        { x: 11, y: 12 },
      ],
    },
    {
      id: 2,
      loop: true,
      pauseSeconds: 0.3,
      points: [
        { x: 19, y: 11 },
        { x: 19, y: 4 },
        { x: 15, y: 12 },
        { x: 19, y: 8 },
      ],
    },
  ],
  dialogue: [
    { at: 'enter', speaker: 'Radio', line: 'Chase Protocol revision twelve. Subject: Squeak. Objective: do not become a sample.' },
    { at: 'enter', speaker: 'Gran', line: 'If it is too white, you are the dirt. Key in the west grate. Doors north. Do not sneeze on the glass.', delay: 0.6 },
    { at: 'firstCheese', speaker: 'Squeak', line: 'Lab cheddar. It hums. I hum back, quieter.' },
    { at: 'firstSpotted', speaker: 'Pounce', line: 'Savannah on the midline. Bengal on the east. You brought a thimble of ice. Cute.' },
    { at: 'halfQuota', speaker: 'Narrator', line: 'Airlocks do not care about quota. They care about pressure, which is a kind of cat.' },
    { at: 'win', speaker: 'Squeak', line: 'Anomaly filed. Whiskers attached. Launch cradle can wait.' },
    { at: 'lose', speaker: 'Pounce', line: 'Sample acquired.' },
    { at: 'idle', speaker: 'Narrator', line: 'A pump in the wall inhales like a sleeping launch.', delay: 8 },
  ],
  hints: {
    ambushSpots: [
      { x: 11, y: 5 },
      { x: 3, y: 4 },
      { x: 19, y: 6 },
    ],
    searchSpots: [
      { x: 10, y: 3 },
      { x: 6, y: 9 },
      { x: 19, y: 4 },
      { x: 16, y: 8 },
    ],
    aggression: 0.92,
    scentBias: 0.3,
    hearingBias: 0.6,
    campHoleChance: 0.16,
    leashRadius: 11,
  },
  objectives: [
    { kind: 'quota', value: 5, optional: false, label: 'Bank 5 cheese' },
    { kind: 'reachExit', value: 1, optional: false, label: 'Return through the west lock' },
    { kind: 'noCatch', value: 1, optional: true, label: 'Remain unsampled' },
  ],
  quota: 5,
  parTime: 150,
  lives: 2,
  ambient: 0.7,
  difficulty: 8.5,
  music: 'moonlab-protocol',
  tags: ['moonLab', 'airlock', 'multi-cat', 'key', 'protocol'],
};

export default stage;
