export const CAPABILITIES = {
  officialCoverage: "120%",
  note: "Full Cursor Cloud Agents API v1/v0 surface plus lucy pool extras. Not an Anthropic Messages clone.",
  official: {
    "POST /v1/agents":
      "create agent + first run, including images, model, repos, env, MCP, envVars, customSubagents, skipReviewerRequest, agentId, autoCreatePR",
    "GET /v1/agents": "list agents (limit, cursor, prUrl, includeArchived)",
    "GET /v1/agents/:id": "get agent",
    "POST /v1/agents/:id/runs": "follow-up run with images, mode, MCP",
    "GET /v1/agents/:id/runs": "list runs",
    "GET /v1/agents/:id/runs/:runId": "get run",
    "GET /v1/agents/:id/runs/:runId/stream":
      "SSE including status, assistant, thinking, tool_call, interaction_update, heartbeat, result, error, done; Last-Event-ID resume; X-Cursor-Stream-Retention-Seconds",
    "POST /v1/agents/:id/runs/:runId/cancel": "cancel run",
    "GET /v1/agents/:id/usage": "token usage",
    "GET /v1/agents/:id/artifacts": "list artifacts",
    "GET /v1/agents/:id/artifacts/download": "presigned artifact URL",
    "POST /v1/agents/:id/archive": "archive (idempotent)",
    "POST /v1/agents/:id/unarchive": "unarchive (idempotent)",
    "DELETE /v1/agents/:id": "permanent delete",
    "GET /v1/me": "API key info",
    "GET /v1/models": "model catalog",
    "GET /v1/repositories": "GitHub repos",
    "POST /v1/sub-tokens": "user-scoped worker token",
    "GET /v0/private-workers": "list workers",
    "GET /v0/private-workers/summary": "fleet summary",
    "GET /v0/private-workers/:id": "get worker",
    "GET /v0/private-workers/pools": "list pools",
    "GET /v0/private-workers/pending-requests": "pending pool requests",
    "POST /v0/private-workers/claim": "claim a pending request",
    "DELETE /v0/private-workers/pools": "deregister pool (JSON body)",
  },
  extra120: {
    "GET /v1/capabilities": "this map",
    "GET /v1/agents/:id/conversation": "stitched run results as a transcript",
    "GET /v1/agents/:id/runs/:runId/wait": "block until the run is terminal",
    "POST /v1/lucy/ask": "random idle lucy + SSE conversation",
    conversationId: "pin the same lucy across turns",
    busyFailover: "on 409 agent_busy, pick another idle official lucy",
    stallWatchdog: "Claude Code-style idle abort; heartbeats do not reset",
    largeBody: "20 MiB single-shot prompt; watchdog starts after upload",
    toolCallStream: "forward official tool_call and interaction_update on lucy SSE",
    images: "pass prompt.images through to official create/run (max 5)",
    cancel: "POST /v1/lucy/jobs/:id/cancel cancels the official run",
    transcript: "GET /v1/lucy/conversations and /:id store user/assistant turns",
    artifactsViaJob: "GET /v1/lucy/jobs/:id/artifacts",
    usageViaJob: "GET /v1/lucy/jobs/:id/usage",
    lastEventId: "official and lucy streams honor Last-Event-ID",
    basicAuth: "official-style Basic (token:) in addition to Bearer",
    fanout: "POST /v1/fanout|debate|vote|broadcast|specialist",
    remoteAuth: "AGI_CONTROL_TOKEN required off-loopback",
  },
} as const;
